import type { CaseFixture, InvestigationQueryReturnedRecord } from "../types";

const caseId = "case-cloud-0421";
const scenarioId = "cloud-identity";
const fixtureVersion = "cloud-identity-v5";

const base = {
  caseId,
  scenarioId,
  fixtureVersion,
  synthetic: true as const,
};

function returnedRecord(
  id: string,
  sourceLabel: string,
  timestamp: string,
  recordType: string,
  entityIds: readonly string[],
  fields: Readonly<Record<string, string>>,
): InvestigationQueryReturnedRecord {
  return {
    id,
    sourceLabel,
    timestamp,
    recordType,
    entityIds,
    fields: Object.entries(fields).map(([label, value]) => ({ label, value })),
  };
}

export const cloudIdentityScenario = {
  id: caseId,
  scenarioId,
  fixtureVersion,
  organization: "Northstar Example Systems",
  classification: "synthetic_demo_data",
  title: "Privileged export outside standard workflow",
  summary:
    "Tier 1 correlated a privileged customer export. The CHG-2941 reference, source egress, and prod-admin use remain unverified until bounded evidence is attached.",
  severity: "high",
  status: "investigating",
  timeRange: {
    start: "2026-08-27T09:22:31Z",
    end: "2026-08-27T09:43:00Z",
  },
  alerts: [
    {
      id: "alert-cloud-session-0421",
      caseId,
      title: "Privileged export outside standard workflow",
      subject: "Jordan Doe · customer-export.csv",
      severity: "high",
      status: "escalated",
      source: "Cross-source correlation",
      occurredAt: "2026-08-27T09:43:00Z",
      selected: true,
    },
    {
      id: "alert-identity-0418",
      caseId,
      title: "New-country sign-in risk",
      subject: "Jordan Doe · Okta",
      severity: "medium",
      status: "linked",
      source: "Okta System Log",
      occurredAt: "2026-08-27T09:22:42Z",
      selected: false,
    },
    {
      id: "alert-data-0409",
      caseId,
      title: "Restricted export access",
      subject: "customer-export.csv · S3",
      severity: "medium",
      status: "linked",
      source: "AWS CloudTrail",
      occurredAt: "2026-08-27T09:42:02Z",
      selected: false,
    },
  ],
  entities: [
    {
      id: "identity:jdoe",
      kind: "identity",
      label: "Jordan Doe",
      provider: "Okta",
      summary: "Human identity in Data Operations",
      accountName: "jdoe",
      email: "jordan.doe@example.test",
      department: "Data Operations",
    },
    {
      id: "session:okta-921",
      kind: "session",
      label: "Federated session 921",
      provider: "Okta",
      summary: "WebAuthn-verified session; source approval is unverified",
      externalSessionId: "00s9R7K2M921",
      sourceIp: "198.51.100.24",
      deviceId: "device-391-jd",
    },
    {
      id: "indicator:198.51.100.24",
      kind: "network_indicator",
      label: "198.51.100.24",
      provider: "Reference inventory",
      summary: "Documented session source; ownership unverified",
      address: "198.51.100.24",
      addressClass: "documentation_range",
    },
    {
      id: "role:prod-admin",
      kind: "cloud_role",
      label: "prod-admin",
      provider: "AWS IAM",
      summary: "Administrative role used instead of the scoped export role",
      roleArn: "arn:aws:iam::111122223333:role/prod-admin",
      privilegeLevel: "administrative",
    },
    {
      id: "secret:prod-db-primary",
      kind: "secret",
      label: "prod/db/primary",
      provider: "AWS Secrets Manager",
      summary: "Database credential read during the privileged export path",
      secretArn:
        "arn:aws:secretsmanager:us-east-1:111122223333:secret:prod/db/primary-7F3K",
      classification: "production_credential",
    },
    {
      id: "object:customer-export",
      kind: "cloud_object",
      label: "customer-export.csv",
      provider: "Amazon S3",
      summary: "Restricted export accessed; change scope unverified",
      bucket: "trace-customer-exports",
      objectKey: "2026-08-27/customer-export.csv",
      classification: "restricted_customer_data",
    },
  ],
  events: [
    {
      ...base,
      id: "EVT-OKTA-0001",
      sequence: 1,
      status: "observed",
      sourceCategory: "identity_telemetry",
      sourceLabel: "Okta System Log",
      timestamp: "2026-08-27T09:22:31Z",
      actor: { kind: "source_system", id: "okta-system-log" },
      action: "user.session.start",
      entityIds: ["identity:jdoe", "session:okta-921"],
      summary: "Jordan Doe started an Okta session.",
      payload: {
        kind: "okta_session_start",
        externalSessionId: "00s9R7K2M921",
        clientIp: "198.51.100.24",
        outcome: "SUCCESS",
      },
    },
    {
      ...base,
      id: "EVT-OKTA-0002",
      sequence: 2,
      status: "observed",
      sourceCategory: "identity_telemetry",
      sourceLabel: "Okta System Log",
      timestamp: "2026-08-27T09:22:36Z",
      actor: { kind: "source_system", id: "okta-system-log" },
      action: "user.authentication.verify",
      entityIds: ["identity:jdoe", "session:okta-921"],
      summary: "WebAuthn verification completed for the session.",
      payload: {
        kind: "okta_mfa_verify",
        externalSessionId: "00s9R7K2M921",
        factor: "webauthn",
        outcome: "SUCCESS",
      },
    },
    {
      ...base,
      id: "EVT-OKTA-0003",
      sequence: 3,
      status: "observed",
      sourceCategory: "identity_telemetry",
      sourceLabel: "Okta System Log",
      timestamp: "2026-08-27T09:22:42Z",
      actor: { kind: "source_system", id: "okta-system-log" },
      action: "policy.evaluate_sign_on",
      entityIds: [
        "identity:jdoe",
        "session:okta-921",
        "indicator:198.51.100.24",
      ],
      summary: "Sign-on policy allowed a session with new-country risk.",
      payload: {
        kind: "okta_policy_evaluation",
        externalSessionId: "00s9R7K2M921",
        clientIp: "198.51.100.24",
        geoRisk: "new_country",
        outcome: "ALLOW",
      },
    },
    {
      ...base,
      id: "EVT-AWS-0004",
      sequence: 4,
      status: "observed",
      sourceCategory: "cloud_audit",
      sourceLabel: "AWS CloudTrail",
      timestamp: "2026-08-27T09:23:07Z",
      actor: { kind: "source_system", id: "aws-cloudtrail" },
      action: "AssumeRoleWithSAML",
      entityIds: ["session:okta-921", "role:prod-admin"],
      summary: "The federated session assumed prod-admin.",
      payload: {
        kind: "aws_assume_role",
        roleArn: "arn:aws:iam::111122223333:role/prod-admin",
        principalId: "AROA7F3K9:jdoe-00s9R7K2M921",
        sourceIdentity: "jdoe",
        sourceIp: "198.51.100.24",
        outcome: "SUCCESS",
      },
    },
    {
      ...base,
      id: "EVT-AWS-0005",
      sequence: 5,
      status: "observed",
      sourceCategory: "cloud_audit",
      sourceLabel: "AWS CloudTrail",
      timestamp: "2026-08-27T09:26:18Z",
      actor: { kind: "source_system", id: "aws-cloudtrail" },
      action: "GetSecretValue",
      entityIds: ["role:prod-admin", "secret:prod-db-primary"],
      summary:
        "The assumed role read the database credential used by the export runbook.",
      payload: {
        kind: "aws_get_secret",
        principalId: "AROA7F3K9:jdoe-00s9R7K2M921",
        secretArn:
          "arn:aws:secretsmanager:us-east-1:111122223333:secret:prod/db/primary-7F3K",
        outcome: "SUCCESS",
      },
    },
    {
      ...base,
      id: "EVT-AWS-0006",
      sequence: 6,
      status: "observed",
      sourceCategory: "cloud_audit",
      sourceLabel: "AWS CloudTrail",
      timestamp: "2026-08-27T09:31:55Z",
      actor: { kind: "source_system", id: "aws-cloudtrail" },
      action: "ListBucket",
      entityIds: ["role:prod-admin", "object:customer-export"],
      summary: "The assumed role listed the customer-export bucket.",
      payload: {
        kind: "aws_list_bucket",
        principalId: "AROA7F3K9:jdoe-00s9R7K2M921",
        bucketName: "trace-customer-exports",
        outcome: "SUCCESS",
      },
    },
    {
      ...base,
      id: "EVT-AWS-0007",
      sequence: 7,
      status: "observed",
      sourceCategory: "cloud_audit",
      sourceLabel: "AWS CloudTrail",
      timestamp: "2026-08-27T09:42:02Z",
      actor: { kind: "source_system", id: "aws-cloudtrail" },
      action: "GetObject",
      entityIds: ["role:prod-admin", "object:customer-export"],
      summary: "The assumed role accessed customer-export.csv.",
      payload: {
        kind: "aws_get_object",
        principalId: "AROA7F3K9:jdoe-00s9R7K2M921",
        bucketName: "trace-customer-exports",
        objectKey: "2026-08-27/customer-export.csv",
        bytesTransferred: 24810392,
        outcome: "SUCCESS",
      },
    },
  ],
  primaryTraceEventIds: [
    "EVT-OKTA-0001",
    "EVT-OKTA-0002",
    "EVT-AWS-0004",
    "EVT-AWS-0005",
    "EVT-AWS-0007",
  ],
  joins: [
    {
      ...base,
      id: "JOIN-CLOUD-01",
      sequence: 8,
      status: "correlated",
      sourceCategory: "deterministic_model",
      sourceLabel: "TRACE correlation",
      timestamp: "2026-08-27T09:43:00Z",
      actor: { kind: "system", id: "trace-correlation-v1" },
      fromEntityId: "identity:jdoe",
      toEntityId: "session:okta-921",
      relation: "authenticated_as",
      matchField: "externalSessionId",
      matchValue: "00s9R7K2M921",
      evidenceIds: ["EVT-OKTA-0001", "EVT-OKTA-0002"],
      label: "Session identifier continuity",
      limitation: "The records identify the account, not the physical user.",
    },
    {
      ...base,
      id: "JOIN-CLOUD-02",
      sequence: 9,
      status: "correlated",
      sourceCategory: "deterministic_model",
      sourceLabel: "TRACE correlation",
      timestamp: "2026-08-27T09:43:00Z",
      actor: { kind: "system", id: "trace-correlation-v1" },
      fromEntityId: "session:okta-921",
      toEntityId: "role:prod-admin",
      relation: "federated_into",
      matchField: "principalId",
      matchValue: "AROA7F3K9:jdoe-00s9R7K2M921",
      evidenceIds: ["EVT-OKTA-0001", "EVT-AWS-0004"],
      label: "Federated principal continuity",
      limitation: "The match links the session and role, not the user intent.",
    },
    {
      ...base,
      id: "JOIN-CLOUD-03",
      sequence: 10,
      status: "correlated",
      sourceCategory: "deterministic_model",
      sourceLabel: "TRACE correlation",
      timestamp: "2026-08-27T09:43:00Z",
      actor: { kind: "system", id: "trace-correlation-v1" },
      fromEntityId: "role:prod-admin",
      toEntityId: "secret:prod-db-primary",
      relation: "read_secret",
      matchField: "principalId",
      matchValue: "AROA7F3K9:jdoe-00s9R7K2M921",
      evidenceIds: ["EVT-AWS-0004", "EVT-AWS-0005"],
      label: "Role principal to secret access",
      limitation: "CloudTrail proves the read, not use of the secret value.",
    },
    {
      ...base,
      id: "JOIN-CLOUD-04",
      sequence: 11,
      status: "correlated",
      sourceCategory: "deterministic_model",
      sourceLabel: "TRACE correlation",
      timestamp: "2026-08-27T09:43:00Z",
      actor: { kind: "system", id: "trace-correlation-v1" },
      fromEntityId: "role:prod-admin",
      toEntityId: "object:customer-export",
      relation: "accessed_object",
      matchField: "principalId",
      matchValue: "AROA7F3K9:jdoe-00s9R7K2M921",
      evidenceIds: ["EVT-AWS-0004", "EVT-AWS-0007"],
      label: "Role principal to object access",
      limitation: "GetObject proves access, not downstream transfer.",
    },
  ],
  enrichments: [
    {
      ...base,
      id: "ENR-CLOUD-IDENTITY-01",
      sequence: 12,
      status: "supporting",
      sourceCategory: "identity_directory",
      sourceLabel: "directory snapshot",
      timestamp: "2026-08-27T09:44:00Z",
      actor: { kind: "system", id: "fixture-directory" },
      entityId: "identity:jdoe",
      title: "Identity and change baseline",
      summary:
        "Jordan owns CHG-2941 and used the assigned device; this supports operator continuity but does not authorize prod-admin.",
      caveat: "records only; no live identity provider was queried.",
      toolName: "enrich_identity",
      payload: {
        kind: "identity_baseline",
        manager: "Casey Rivera",
        normalRole: "data-export-operator",
        priorProdAdminSessions30d: 1,
        knownDevice: true,
      },
    },
    {
      ...base,
      id: "ENR-CLOUD-NETWORK-01",
      sequence: 13,
      status: "supporting",
      sourceCategory: "network_inventory",
      sourceLabel: "network inventory",
      timestamp: "2026-08-27T09:44:15Z",
      actor: { kind: "system", id: "fixture-network-inventory" },
      entityId: "indicator:198.51.100.24",
      title: "Source network context",
      summary:
        "The address maps to the approved London corporate VPN POP for the export window.",
      caveat:
        "198.51.100.24 is reserved for documentation; no real ownership claim is made.",
      toolName: "enrich_network_indicator",
      payload: {
        kind: "network_context",
        addressClass: "documentation_range",
        geoClassification: "new_country",
        priorIdentitySessions30d: 0,
        inventoryMatch: true,
        approvedContext: "CHG-2941 · London corporate VPN POP",
      },
    },
    {
      ...base,
      id: "ENR-CLOUD-ROLE-01",
      sequence: 14,
      status: "disputed",
      sourceCategory: "cloud_configuration",
      sourceLabel: "IAM snapshot",
      timestamp: "2026-08-27T09:44:30Z",
      actor: { kind: "system", id: "fixture-iam" },
      entityId: "role:prod-admin",
      title: "Role posture",
      summary:
        "The task was approved, but prod-admin exceeds the scoped export role required by policy.",
      caveat:
        "The simplified model does not evaluate every AWS policy condition.",
      toolName: "enrich_cloud_role",
      payload: {
        kind: "role_posture",
        federationTrust: "Okta SAML provider",
        effectivePrivilege: "AdministratorAccess",
        maximumSessionHours: 4,
        mfaRequired: true,
      },
    },
    {
      ...base,
      id: "ENR-CLOUD-OBJECT-01",
      sequence: 15,
      status: "supporting",
      sourceCategory: "asset_inventory",
      sourceLabel: "object inventory",
      timestamp: "2026-08-27T09:44:45Z",
      actor: { kind: "system", id: "fixture-object-inventory" },
      entityId: "object:customer-export",
      title: "Export authorization",
      summary:
        "CHG-2941 covers this object and size during 09:00–11:00 UTC, but it does not authorize prod-admin.",
      caveat:
        "Fixed synthetic approval scope; this result corrects the initial assumption that the change also approved the role.",
      toolName: "enrich_resource",
      payload: {
        kind: "object_inventory",
        classification: "Customer data · restricted",
        sizeBytes: 24810392,
        priorReadsByIdentity90d: 1,
        approvedExportWindow: "CHG-2941 · 09:00–11:00 UTC",
      },
    },
  ],
  investigationQueries: [
    {
      id: "QRY-CLOUD-IDENTITY-01",
      title: "Operator and change baseline",
      question:
        "Does this operator, device, and change record match prior approved work?",
      objective:
        "Reconcile the session identity with device ownership, prior role use, and CHG-2941.",
      targetEntityId: "identity:jdoe",
      toolName: "enrich_identity",
      resultArtifactId: "ENR-CLOUD-IDENTITY-01",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "identity directory",
          sourceCategory: "identity_directory",
          timeRange: {
            start: "2026-05-29T09:00:00Z",
            end: "2026-08-27T09:43:00Z",
          },
          syntheticRecordCount: 420,
        },
        {
          sourceLabel: "Okta event lake",
          sourceCategory: "identity_telemetry",
          timeRange: {
            start: "2026-07-28T09:00:00Z",
            end: "2026-08-27T09:43:00Z",
          },
          syntheticRecordCount: 1180,
        },
      ],
      matchedRecordCount: 3,
      returnedRecordCount: 2,
      returnedRecords: [
        returnedRecord(
          "QRR-CLOUD-IDENTITY-01",
          "identity directory",
          "2026-08-27T09:22:31Z",
          "Directory assignment",
          ["identity:jdoe"],
          {
            Account: "jdoe",
            Device: "NXS-LT-227",
            Manager: "Casey Rivera",
          },
        ),
        returnedRecord(
          "QRR-CLOUD-IDENTITY-02",
          "Okta event lake",
          "2026-08-27T09:22:31Z",
          "Session baseline",
          ["identity:jdoe", "session:okta-921"],
          {
            Session: "921",
            Device: "NXS-LT-227",
            "Prior prod-admin sessions": "1 in 30 days",
          },
        ),
      ],
      resultChange:
        "Known device and CHG-2941 ownership support operator continuity; authorization remains unresolved.",
      caveat:
        "Bounded deterministic fixture; no identity provider was queried.",
    },
    {
      id: "QRY-CLOUD-EGRESS-02",
      title: "Source egress resolution",
      question: "Is the new-country source approved corporate egress?",
      objective:
        "Compare the session source with the VPN inventory and identity-session history.",
      targetEntityId: "indicator:198.51.100.24",
      toolName: "enrich_network_indicator",
      resultArtifactId: "ENR-CLOUD-NETWORK-01",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "VPN inventory",
          sourceCategory: "network_inventory",
          timeRange: {
            start: "2026-08-20T00:00:00Z",
            end: "2026-08-27T09:43:00Z",
          },
          syntheticRecordCount: 86,
        },
        {
          sourceLabel: "identity session index",
          sourceCategory: "identity_telemetry",
          timeRange: {
            start: "2026-07-28T00:00:00Z",
            end: "2026-08-27T09:43:00Z",
          },
          syntheticRecordCount: 960,
        },
      ],
      matchedRecordCount: 2,
      returnedRecordCount: 2,
      returnedRecords: [
        returnedRecord(
          "QRR-CLOUD-EGRESS-01",
          "VPN inventory",
          "2026-08-27T09:22:31Z",
          "VPN point of presence",
          ["indicator:198.51.100.24"],
          {
            Address: "198.51.100.24",
            Location: "London",
            Status: "Approved corporate egress",
          },
        ),
        returnedRecord(
          "QRR-CLOUD-EGRESS-02",
          "identity session index",
          "2026-08-27T09:22:31Z",
          "Session source",
          ["session:okta-921", "indicator:198.51.100.24"],
          {
            Session: "921",
            Source: "198.51.100.24",
            "Approved context": "CHG-2941",
          },
        ),
      ],
      resultChange:
        "The documentation address maps to the approved London VPN POP in the fixture.",
      caveat:
        "The address is documentation-range data; the result makes no real ownership claim.",
    },
    {
      id: "QRY-CLOUD-ROLE-03",
      title: "Effective privilege comparison",
      question:
        "Did prod-admin exceed the privilege required by the approved workflow?",
      objective:
        "Resolve federation trust, effective policy, and comparable export-role sessions.",
      targetEntityId: "role:prod-admin",
      toolName: "enrich_cloud_role",
      resultArtifactId: "ENR-CLOUD-ROLE-01",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "IAM policy graph",
          sourceCategory: "cloud_configuration",
          timeRange: {
            start: "2026-08-01T00:00:00Z",
            end: "2026-08-27T09:43:00Z",
          },
          syntheticRecordCount: 440,
        },
        {
          sourceLabel: "CloudTrail role corpus",
          sourceCategory: "cloud_audit",
          timeRange: {
            start: "2026-05-29T00:00:00Z",
            end: "2026-08-27T09:43:00Z",
          },
          syntheticRecordCount: 1960,
        },
      ],
      matchedRecordCount: 4,
      returnedRecordCount: 3,
      returnedRecords: [
        returnedRecord(
          "QRR-CLOUD-ROLE-01",
          "IAM policy graph",
          "2026-08-27T09:43:00Z",
          "Role policy",
          ["role:prod-admin"],
          {
            Role: "prod-admin",
            Privilege: "AdministratorAccess",
            "Maximum session": "4 hours",
          },
        ),
        returnedRecord(
          "QRR-CLOUD-ROLE-02",
          "IAM policy graph",
          "2026-08-27T09:43:00Z",
          "Approved workflow role",
          ["role:prod-admin"],
          {
            Required: "data-export-operator",
            Observed: "prod-admin",
            Result: "Privilege exceeds workflow",
          },
        ),
        returnedRecord(
          "QRR-CLOUD-ROLE-03",
          "CloudTrail role corpus",
          "2026-08-27T09:43:00Z",
          "Comparable role use",
          ["identity:jdoe", "role:prod-admin"],
          {
            Principal: "jdoe",
            "Prior role use": "1 in 30 days",
            MFA: "Required",
          },
        ),
      ],
      resultChange:
        "prod-admin exceeds the scoped export role; the change reference alone cannot authorize that role.",
      caveat:
        "This bounded analysis does not evaluate every AWS policy condition.",
    },
    {
      id: "QRY-CLOUD-EXPORT-04",
      title: "Export authorization reconciliation",
      question: "Was this exact object read inside the approved export window?",
      objective:
        "Join CloudTrail access, object inventory, and the approved change window.",
      targetEntityId: "object:customer-export",
      toolName: "enrich_resource",
      resultArtifactId: "ENR-CLOUD-OBJECT-01",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "restricted-object audit",
          sourceCategory: "cloud_audit",
          timeRange: {
            start: "2026-08-27T08:30:00Z",
            end: "2026-08-27T10:00:00Z",
          },
          syntheticRecordCount: 218,
        },
        {
          sourceLabel: "change and object inventory",
          sourceCategory: "asset_inventory",
          timeRange: {
            start: "2026-05-29T00:00:00Z",
            end: "2026-08-27T10:00:00Z",
          },
          syntheticRecordCount: 65,
        },
      ],
      matchedRecordCount: 2,
      returnedRecordCount: 2,
      returnedRecords: [
        returnedRecord(
          "QRR-CLOUD-EXPORT-01",
          "restricted-object audit",
          "2026-08-27T09:43:00Z",
          "Object access",
          ["role:prod-admin", "object:customer-export"],
          {
            Object: "customer-export.csv",
            "Bytes read": "23.7 MB",
            Principal: "prod-admin",
          },
        ),
        returnedRecord(
          "QRR-CLOUD-EXPORT-02",
          "change and object inventory",
          "2026-08-27T09:43:00Z",
          "Change scope",
          ["identity:jdoe", "object:customer-export"],
          {
            Change: "CHG-2941",
            Window: "09:00–11:00 UTC",
            Role: "Not authorized",
          },
        ),
      ],
      resultChange:
        "CHG-2941 covers the object and time window, but not the prod-admin role; analyst interpretation is required.",
      caveat: "The approval and access baseline are fixed synthetic values.",
    },
  ],
  tier1Escalation: {
    ...base,
    id: "T1-ESC-CLOUD-0421",
    sequence: 16,
    status: "correlated",
    sourceCategory: "deterministic_model",
    sourceLabel: "Tier 1 triage",
    timestamp: "2026-08-27T09:43:00Z",
    actor: { kind: "tier1_ai", id: "tier1-triage-01" },
    confidence: "medium",
    escalationReason:
      "A new-country session assumed prod-admin, read a production credential, and accessed a restricted export. Tier 1 could not verify the change record or VPN inventory.",
    evidenceIds: [
      "EVT-OKTA-0001",
      "EVT-OKTA-0003",
      "EVT-AWS-0004",
      "EVT-AWS-0005",
      "EVT-AWS-0007",
    ],
    observations: [
      {
        id: "T1-OBS-CLOUD-SESSION",
        status: "correlated",
        title: "New-country session assumed prod-admin",
        summary:
          "The allowed session with new-country risk and the prod-admin assumption share the same visible federated identity.",
        entityIds: [
          "session:okta-921",
          "indicator:198.51.100.24",
          "role:prod-admin",
        ],
        evidenceIds: ["EVT-OKTA-0003", "EVT-AWS-0004"],
      },
      {
        id: "T1-OBS-CLOUD-ACCESS",
        status: "correlated",
        title: "Privileged role reached restricted data",
        summary:
          "prod-admin read the export-runbook credential and accessed customer-export.csv in the same session chain.",
        entityIds: [
          "role:prod-admin",
          "secret:prod-db-primary",
          "object:customer-export",
        ],
        evidenceIds: ["EVT-AWS-0005", "EVT-AWS-0007"],
      },
    ],
    recommendedSteps: [
      {
        id: "T1-STEP-CLOUD-IDENTITY",
        status: "proposed",
        label: "Verify operator and change ownership",
        objective:
          "Attach the identity baseline for Jordan Doe before classifying the session.",
        recommendedTool: "enrich_identity",
        entityId: "identity:jdoe",
        evidenceIds: ["EVT-OKTA-0003", "EVT-AWS-0004"],
        completionArtifactId: "ENR-CLOUD-IDENTITY-01",
        investigationQueryId: "QRY-CLOUD-IDENTITY-01",
      },
      {
        id: "T1-STEP-CLOUD-EGRESS",
        status: "proposed",
        label: "Verify the source egress",
        objective:
          "Attach approved-network context before treating the geography signal as hostile.",
        recommendedTool: "enrich_network_indicator",
        entityId: "indicator:198.51.100.24",
        evidenceIds: ["EVT-OKTA-0003"],
        completionArtifactId: "ENR-CLOUD-NETWORK-01",
        investigationQueryId: "QRY-CLOUD-EGRESS-02",
      },
      {
        id: "T1-STEP-CLOUD-ROLE",
        status: "proposed",
        label: "Compare role use to policy",
        objective:
          "Attach role posture to determine whether prod-admin exceeded the approved workflow.",
        recommendedTool: "enrich_cloud_role",
        entityId: "role:prod-admin",
        evidenceIds: ["EVT-AWS-0004", "EVT-AWS-0007"],
        completionArtifactId: "ENR-CLOUD-ROLE-01",
        investigationQueryId: "QRY-CLOUD-ROLE-03",
      },
      {
        id: "T1-STEP-CLOUD-EXPORT",
        status: "proposed",
        label: "Verify export authorization",
        objective:
          "Attach object and change-window context for customer-export.csv.",
        recommendedTool: "enrich_resource",
        entityId: "object:customer-export",
        evidenceIds: ["EVT-AWS-0007"],
        completionArtifactId: "ENR-CLOUD-OBJECT-01",
        investigationQueryId: "QRY-CLOUD-EXPORT-04",
      },
    ],
    checksCompleted: [
      "Identity and session continuity",
      "Role-assumption correlation",
      "Secret and object access correlation",
    ],
    unresolvedQuestions: [
      "Hypothesis: CHG-2941 covers the object and time window; verify whether it also authorizes prod-admin.",
      "Is the source approved corporate VPN egress?",
      "Why was prod-admin used instead of the scoped export role?",
    ],
    actionsWithheld: [
      "No session revocation",
      "No IAM policy change",
      "No evidence disposition",
    ],
  },
  decision: {
    ...base,
    id: "DEC-CLOUD-01",
    sequence: 17,
    status: "disputed",
    sourceCategory: "analyst_judgment",
    sourceLabel: "Analyst decision",
    timestamp: "2026-08-27T09:45:00Z",
    actor: { kind: "analyst", id: "analyst-01" },
    question:
      "Does CHG-2941 authorize this export after correcting for prod-admin use?",
    options: [
      {
        id: "authorized_exception",
        label: "Authorized after correction · record exception",
        rationale:
          "The change record, VPN inventory, assigned device, and object window corroborate the export. CHG-2941 does not authorize prod-admin; record that role use as an exception.",
      },
      {
        id: "keep_suspect",
        label: "Keep suspect",
        rationale:
          "The supporting context does not sufficiently explain the privileged role and restricted data access.",
      },
    ],
    requiresEnrichmentIds: [
      "ENR-CLOUD-IDENTITY-01",
      "ENR-CLOUD-NETWORK-01",
      "ENR-CLOUD-OBJECT-01",
    ],
    evidenceIds: ["EVT-OKTA-0003", "EVT-AWS-0007"],
    effect: "Records the case disposition without changing observed evidence.",
  },
  reachability: {
    ...base,
    id: "MODEL-CLOUD-REACH-01",
    sequence: 18,
    status: "modeled",
    sourceCategory: "deterministic_model",
    sourceLabel: "Graph reachability model v1",
    timestamp: "2026-08-27T09:46:15Z",
    actor: { kind: "system", id: "graph-reachability-v1" },
    model: "graph_reachability_v1",
    sourceEntityId: "identity:jdoe",
    assumption:
      "The observed prod-admin session remains valid and the simplified role snapshot is accurate.",
    reachableEntityIds: ["secret:prod-db-primary", "object:customer-export"],
    paths: [
      {
        id: "PATH-CLOUD-01",
        entityIds: [
          "identity:jdoe",
          "session:okta-921",
          "role:prod-admin",
          "secret:prod-db-primary",
        ],
      },
      {
        id: "PATH-CLOUD-02",
        entityIds: [
          "identity:jdoe",
          "session:okta-921",
          "role:prod-admin",
          "object:customer-export",
        ],
      },
    ],
    caveat: "Reachable does not mean accessed beyond the observed events.",
  },
  counterfactual: {
    ...base,
    id: "MODEL-CLOUD-CF-01",
    sequence: 19,
    status: "simulated",
    sourceCategory: "deterministic_model",
    sourceLabel: "Control simulation v1",
    timestamp: "2026-08-27T09:46:30Z",
    actor: { kind: "system", id: "control-simulation-v1" },
    control: "remove_role_trust",
    changedEntityId: "role:prod-admin",
    severedPathIds: ["PATH-CLOUD-01", "PATH-CLOUD-02"],
    remainingPathIds: [],
    caveat: "The simulation does not revoke a session or execute a control.",
  },
  stream: { mode: "deterministic_manual_replay", stages: [] },
  responseActions: [],
  presentation: {
    defaultEvidenceView: "trace",
    graphWidth: 1160,
    graphHeight: 650,
    nodes: [
      { entityId: "identity:jdoe", x: 80, y: 190, lane: "entry" },
      { entityId: "session:okta-921", x: 310, y: 190, lane: "entry" },
      { entityId: "indicator:198.51.100.24", x: 310, y: 410, lane: "entry" },
      { entityId: "role:prod-admin", x: 550, y: 190, lane: "access" },
      { entityId: "object:customer-export", x: 850, y: 90, lane: "impact" },
      { entityId: "secret:prod-db-primary", x: 850, y: 330, lane: "impact" },
    ],
    stageQuestions: [
      "Can the observed identity-to-data path be reconciled with an approved change without dismissing the role-control exception?",
    ],
    coverageNotes: [
      "Evidence confirms the cloud API activity and approved-task context. It does not establish the physical operator or downstream file handling.",
    ],
    command: {
      observed: "prod-admin accessed customer-export.csv",
      initialScope: "Approved change and VPN context are not yet attached",
      stageScopes: [],
      scopeMilestones: [
        {
          requiresEnrichmentIds: ["ENR-CLOUD-IDENTITY-01"],
          summary:
            "Assigned device and CHG-2941 ownership attached · VPN and object authorization pending",
        },
        {
          requiresEnrichmentIds: [
            "ENR-CLOUD-IDENTITY-01",
            "ENR-CLOUD-NETWORK-01",
          ],
          summary:
            "Assigned device and approved VPN attached · object authorization pending",
        },
        {
          requiresEnrichmentIds: [
            "ENR-CLOUD-IDENTITY-01",
            "ENR-CLOUD-NETWORK-01",
            "ENR-CLOUD-OBJECT-01",
          ],
          summary:
            "CHG-2941 covers the object and window · prod-admin remains unapproved and physical operator remains unproven",
        },
      ],
    },
  },
  impact: {
    observedEntityIds: [
      "identity:jdoe",
      "session:okta-921",
      "role:prod-admin",
      "secret:prod-db-primary",
      "object:customer-export",
    ],
    atRiskEntityIds: [],
    blockedJoinIds: [],
    initialHeadline:
      "One observed identity path · authorization and role scope unresolved",
    modeledHeadline:
      "One observed identity path · authorization corrected; role exception recorded",
    containedHeadline: "Authorized task · least-privilege exception recorded",
  },
  conclusion: {
    reportId: "REPORT-CLOUD-0421",
    reportVersion: "case-report-v1",
    disposition: "authorized_activity_policy_exception",
    title: "Authorized export after a privileged-role correction",
    executiveSummary:
      "The observed session, VPN source, assigned device, and export object align with the scoped portion of CHG-2941. The analyst must correct the initial interpretation: CHG-2941 does not authorize prod-admin. No containment is warranted; the role use is a least-privilege exception.",
    confirmedFindings: [
      "WebAuthn-verified access used the assigned device and approved VPN POP.",
      "CHG-2941 covered the observed export object, size, and time window only.",
      "prod-admin was not authorized by CHG-2941 and exceeded the scoped export role.",
    ],
    limitations: [
      "The identity records do not prove the physical operator.",
      "No endpoint or downstream transfer telemetry is included in this fixture.",
    ],
    residualRisk: [
      "Review why the scoped data-export role was not used.",
      "Reduce the prod-admin session duration and enforce role selection policy.",
    ],
    requiredDecision: "authorized_exception",
    requiredEnrichmentIds: [
      "ENR-CLOUD-IDENTITY-01",
      "ENR-CLOUD-NETWORK-01",
      "ENR-CLOUD-ROLE-01",
      "ENR-CLOUD-OBJECT-01",
    ],
    requiredActionIds: [],
  },
} satisfies CaseFixture;
