import type { CaseFixture, InvestigationQueryReturnedRecord } from "../types";

const caseId = "case-endpoint-0448";
const scenarioId = "endpoint-lateral";
const fixtureVersion = "endpoint-lateral-v4";

const base = {
  caseId,
  scenarioId,
  fixtureVersion,
  synthetic: true as const,
};

function returnedRecord(
  id: string,
  sourceLabel: string,
  timestamp: string,
  recordType: string,
  entityIds: readonly string[],
  fields: Readonly<Record<string, string>>,
): InvestigationQueryReturnedRecord {
  return {
    id,
    sourceLabel,
    timestamp,
    recordType,
    entityIds,
    fields: Object.entries(fields).map(([label, value]) => ({ label, value })),
  };
}

export const endpointLateralScenario = {
  id: caseId,
  scenarioId,
  fixtureVersion,
  organization: "Northstar Example Systems",
  classification: "synthetic_demo_data",
  title: "Execution with early lateral movement",
  summary:
    "An unsigned helper on FIN-WS-044 made two TLS connections 60 seconds apart. The same host then showed an out-of-scope service-identity logon, a remote service-control attempt, and a production credential read.",
  severity: "critical",
  status: "investigating",
  timeRange: {
    start: "2026-08-28T14:02:11Z",
    end: "2026-08-28T14:06:14Z",
  },
  alerts: [
    {
      id: "alert-endpoint-0448",
      caseId,
      title: "Unsigned helper with repeated egress",
      subject: "FIN-WS-044 · invoice-sync-helper.exe",
      severity: "high",
      status: "escalated",
      source: "EDR correlation",
      occurredAt: "2026-08-28T14:04:34Z",
      selected: true,
    },
    {
      id: "alert-identity-0449",
      caseId,
      title: "Service identity outside expected scope",
      subject: "svc-fin-reports · APP-SRV-021",
      severity: "high",
      status: "linked",
      source: "Windows authentication",
      occurredAt: "2026-08-28T14:04:03Z",
      selected: false,
    },
    {
      id: "alert-cloud-0450",
      caseId,
      title: "Production deployment credential read",
      subject: "svc-fin-reports · ci/deploy/production",
      severity: "high",
      status: "linked",
      source: "cloud audit",
      occurredAt: "2026-08-28T14:05:02Z",
      selected: false,
    },
  ],
  entities: [
    {
      id: "file:invoice-sync-helper",
      kind: "file",
      label: "invoice-sync-helper.exe",
      provider: "EDR",
      summary: "Unsigned, zero-prevalence file in writable path",
      fileName: "invoice-sync-helper.exe",
      sha256:
        "65fb21f3b3b11f7a7d45f31965dad35935e6d9c860ca6f618999510db74260b9",
      classification: "untrusted_executable",
    },
    {
      id: "endpoint:fin-ws-044",
      kind: "endpoint",
      label: "FIN-WS-044",
      provider: "EDR",
      summary: "Finance workstation assigned to Maya Chen",
      hostname: "FIN-WS-044",
      deviceId: "edr-fin-044",
      platform: "windows",
      assetCriticality: "standard",
    },
    {
      id: "indicator:203.0.113.91",
      kind: "network_indicator",
      label: "203.0.113.91",
      provider: "proxy",
      summary: "Documentation-range destination absent from approved egress",
      address: "203.0.113.91",
      addressClass: "documentation_range",
    },
    {
      id: "identity:svc-fin-reports",
      kind: "identity",
      label: "svc-fin-reports",
      provider: "directory",
      summary: "Service identity scoped to the finance reporting service",
      accountName: "svc-fin-reports",
      email: "svc-fin-reports@example.test",
      department: "Finance Systems",
    },
    {
      id: "endpoint:app-srv-021",
      kind: "endpoint",
      label: "APP-SRV-021",
      provider: "EDR",
      summary: "Tier 1 production application host",
      hostname: "APP-SRV-021",
      deviceId: "edr-app-021",
      platform: "windows",
      assetCriticality: "tier_1",
    },
    {
      id: "secret:ci-deploy-token",
      kind: "secret",
      label: "ci/deploy/production",
      provider: "secret store",
      summary: "Production deployment credential read by svc-fin-reports",
      secretArn:
        "arn:aws:secretsmanager:us-east-1:111122223333:secret:ci/deploy/production-A81C",
      classification: "deployment_credential",
    },
    {
      id: "workload:billing-api",
      kind: "workload",
      label: "billing-api",
      provider: "deployment policy",
      summary:
        "Modeled target through the deployment credential; image not observed",
      workloadId: "billing-api",
      environment: "production",
      currentImage: null,
      knownGoodImage: null,
    },
  ],
  events: [
    {
      ...base,
      id: "EVT-EDR-0448-01",
      sequence: 1,
      status: "observed",
      sourceCategory: "endpoint_telemetry",
      sourceLabel: "EDR",
      timestamp: "2026-08-28T14:02:11Z",
      actor: { kind: "source_system", id: "fixture-edr" },
      action: "ProcessStart",
      entityIds: ["file:invoice-sync-helper", "endpoint:fin-ws-044"],
      summary:
        "explorer.exe started invoice-sync-helper.exe from Maya Chen's temporary directory.",
      payload: {
        kind: "edr_process_start",
        hostname: "FIN-WS-044",
        deviceId: "edr-fin-044",
        processName: "invoice-sync-helper.exe",
        parentProcess: "explorer.exe",
        imagePath:
          "C:\\Users\\maya.chen\\AppData\\Local\\Temp\\invoice-sync-helper.exe",
        processGuid: "PG-0448-A",
        signer: "unsigned",
        commandLineDisplay:
          "invoice-sync-helper.exe --sync-profile finance-quarterly",
        outcome: "OBSERVED",
      },
    },
    {
      ...base,
      id: "EVT-EDR-0448-02",
      sequence: 2,
      status: "observed",
      sourceCategory: "endpoint_telemetry",
      sourceLabel: "EDR",
      timestamp: "2026-08-28T14:02:14Z",
      actor: { kind: "source_system", id: "fixture-edr" },
      action: "FileWrite",
      entityIds: ["file:invoice-sync-helper", "endpoint:fin-ws-044"],
      summary: "The helper wrote state into C:\\ProgramData\\InvoiceSync.",
      payload: {
        kind: "edr_file_write",
        hostname: "FIN-WS-044",
        deviceId: "edr-fin-044",
        processGuid: "PG-0448-A",
        filePath: "C:\\ProgramData\\InvoiceSync\\invoice-sync.state",
        outcome: "OBSERVED",
      },
    },
    {
      ...base,
      id: "EVT-EDR-0448-03",
      sequence: 3,
      status: "observed",
      sourceCategory: "endpoint_telemetry",
      sourceLabel: "EDR",
      timestamp: "2026-08-28T14:02:20Z",
      actor: { kind: "source_system", id: "fixture-edr" },
      action: "NetworkConnection",
      entityIds: ["endpoint:fin-ws-044", "indicator:203.0.113.91"],
      summary:
        "The helper opened TLS/443 to 203.0.113.91 and sent 14,336 bytes.",
      payload: {
        kind: "edr_network_connection",
        hostname: "FIN-WS-044",
        deviceId: "edr-fin-044",
        processName: "invoice-sync-helper.exe",
        destinationIp: "203.0.113.91",
        destinationPort: 443,
        protocol: "TLS",
        intervalSeconds: 60,
        bytesSent: 14336,
        outcome: "OBSERVED",
      },
    },
    {
      ...base,
      id: "EVT-EDR-0448-04",
      sequence: 4,
      status: "observed",
      sourceCategory: "endpoint_telemetry",
      sourceLabel: "EDR",
      timestamp: "2026-08-28T14:03:20Z",
      actor: { kind: "source_system", id: "fixture-edr" },
      action: "NetworkConnection",
      entityIds: ["endpoint:fin-ws-044", "indicator:203.0.113.91"],
      summary: "The same process repeated TLS/443 egress after 60 seconds.",
      payload: {
        kind: "edr_network_connection",
        hostname: "FIN-WS-044",
        deviceId: "edr-fin-044",
        processName: "invoice-sync-helper.exe",
        destinationIp: "203.0.113.91",
        destinationPort: 443,
        protocol: "TLS",
        intervalSeconds: 60,
        bytesSent: 12928,
        outcome: "OBSERVED",
      },
    },
    {
      ...base,
      id: "EVT-AUTH-0448-05",
      sequence: 5,
      status: "observed",
      sourceCategory: "windows_authentication",
      sourceLabel: "Windows authentication",
      timestamp: "2026-08-28T14:04:03Z",
      actor: { kind: "source_system", id: "fixture-windows-auth" },
      action: "NetworkLogon",
      entityIds: [
        "endpoint:fin-ws-044",
        "identity:svc-fin-reports",
        "endpoint:app-srv-021",
      ],
      summary: "svc-fin-reports logged on to APP-SRV-021 from FIN-WS-044.",
      payload: {
        kind: "windows_network_logon",
        accountName: "svc-fin-reports",
        sourceHostname: "FIN-WS-044",
        targetHostname: "APP-SRV-021",
        logonType: 3,
        logonId: "0xA0448",
        outcome: "SUCCESS",
      },
    },
    {
      ...base,
      id: "EVT-EDR-0448-06",
      sequence: 6,
      status: "observed",
      sourceCategory: "endpoint_telemetry",
      sourceLabel: "EDR",
      timestamp: "2026-08-28T14:04:07Z",
      actor: { kind: "source_system", id: "fixture-edr" },
      action: "ProcessStart",
      entityIds: ["file:invoice-sync-helper", "endpoint:fin-ws-044"],
      summary: "The helper launched a local identity-discovery command.",
      payload: {
        kind: "edr_process_start",
        hostname: "FIN-WS-044",
        deviceId: "edr-fin-044",
        processName: "cmd.exe",
        parentProcess: "invoice-sync-helper.exe",
        imagePath: "C:\\Windows\\System32\\cmd.exe",
        processGuid: "PG-0448-B",
        signer: "signed",
        commandLineDisplay: "cmd.exe /c whoami /all",
        outcome: "OBSERVED",
      },
    },
    {
      ...base,
      id: "EVT-EDR-0448-07",
      sequence: 7,
      status: "observed",
      sourceCategory: "endpoint_telemetry",
      sourceLabel: "EDR",
      timestamp: "2026-08-28T14:04:19Z",
      actor: { kind: "source_system", id: "fixture-edr" },
      action: "ProcessStart",
      entityIds: [
        "file:invoice-sync-helper",
        "endpoint:fin-ws-044",
        "endpoint:app-srv-021",
      ],
      summary:
        "The helper queried the remote service controller on APP-SRV-021.",
      payload: {
        kind: "edr_process_start",
        hostname: "FIN-WS-044",
        deviceId: "edr-fin-044",
        processName: "sc.exe",
        parentProcess: "invoice-sync-helper.exe",
        imagePath: "C:\\Windows\\System32\\sc.exe",
        processGuid: "PG-0448-C",
        signer: "signed",
        commandLineDisplay: "sc.exe \\\\APP-SRV-021 query",
        outcome: "OBSERVED",
      },
    },
    {
      ...base,
      id: "EVT-CLOUD-0448-08",
      sequence: 8,
      status: "observed",
      sourceCategory: "cloud_audit",
      sourceLabel: "cloud audit",
      timestamp: "2026-08-28T14:05:02Z",
      actor: { kind: "source_system", id: "fixture-cloud-audit" },
      action: "GetSecretValue",
      entityIds: ["identity:svc-fin-reports", "secret:ci-deploy-token"],
      summary: "svc-fin-reports read ci/deploy/production.",
      payload: {
        kind: "cloud_secret_read",
        principalId: "svc-fin-reports",
        secretRef: "ci/deploy/production",
        outcome: "SUCCESS",
      },
    },
    {
      ...base,
      id: "EVT-CLOUD-0448-09",
      sequence: 9,
      status: "observed",
      sourceCategory: "cloud_audit",
      sourceLabel: "cloud audit",
      timestamp: "2026-08-28T14:05:12Z",
      actor: { kind: "source_system", id: "fixture-cloud-audit" },
      action: "GetCallerIdentity",
      entityIds: ["identity:svc-fin-reports"],
      summary:
        "The same identity queried its cloud principal; no deployment call followed.",
      payload: {
        kind: "aws_caller_identity",
        principalId: "svc-fin-reports",
        accountId: "111122223333",
        outcome: "SUCCESS",
      },
    },
  ],
  primaryTraceEventIds: [
    "EVT-EDR-0448-01",
    "EVT-EDR-0448-03",
    "EVT-AUTH-0448-05",
    "EVT-EDR-0448-07",
    "EVT-CLOUD-0448-08",
  ],
  joins: [
    {
      ...base,
      id: "JOIN-LAT-01",
      sequence: 10,
      status: "correlated",
      sourceCategory: "deterministic_model",
      sourceLabel: "TRACE correlation",
      timestamp: "2026-08-28T14:05:15Z",
      actor: { kind: "system", id: "trace-correlation-v1" },
      fromEntityId: "file:invoice-sync-helper",
      toEntityId: "endpoint:fin-ws-044",
      relation: "executed_on",
      matchField: "deviceId + processGuid",
      matchValue: "edr-fin-044 + PG-0448-A",
      evidenceIds: ["EVT-EDR-0448-01", "EVT-EDR-0448-02"],
      label: "Helper execution on finance workstation",
      limitation:
        "The process telemetry does not identify who placed the file.",
    },
    {
      ...base,
      id: "JOIN-LAT-02",
      sequence: 11,
      status: "correlated",
      sourceCategory: "deterministic_model",
      sourceLabel: "TRACE correlation",
      timestamp: "2026-08-28T14:05:15Z",
      actor: { kind: "system", id: "trace-correlation-v1" },
      fromEntityId: "endpoint:fin-ws-044",
      toEntityId: "indicator:203.0.113.91",
      relation: "connected_to",
      matchField: "processGuid + interval",
      matchValue: "PG-0448-A + 60s",
      evidenceIds: ["EVT-EDR-0448-03", "EVT-EDR-0448-04"],
      label: "Two process-bound TLS connections",
      limitation: "Connection content and destination ownership are unknown.",
    },
    {
      ...base,
      id: "JOIN-LAT-03",
      sequence: 12,
      status: "correlated",
      sourceCategory: "deterministic_model",
      sourceLabel: "TRACE correlation",
      timestamp: "2026-08-28T14:05:15Z",
      actor: { kind: "system", id: "trace-correlation-v1" },
      fromEntityId: "endpoint:fin-ws-044",
      toEntityId: "identity:svc-fin-reports",
      relation: "used_identity",
      matchField: "sourceHostname + timeline",
      matchValue: "FIN-WS-044 + 14:04Z",
      evidenceIds: ["EVT-AUTH-0448-05", "EVT-EDR-0448-06"],
      label: "Endpoint to service identity continuity",
      limitation: "The events do not show how the credential became available.",
    },
    {
      ...base,
      id: "JOIN-LAT-04",
      sequence: 13,
      status: "correlated",
      sourceCategory: "deterministic_model",
      sourceLabel: "TRACE correlation",
      timestamp: "2026-08-28T14:05:15Z",
      actor: { kind: "system", id: "trace-correlation-v1" },
      fromEntityId: "identity:svc-fin-reports",
      toEntityId: "endpoint:app-srv-021",
      relation: "authenticated_to",
      matchField: "targetHostname + logonId",
      matchValue: "APP-SRV-021 + 0xA0448",
      evidenceIds: ["EVT-AUTH-0448-05", "EVT-EDR-0448-07"],
      label: "Unexpected application-host authentication",
      limitation:
        "Authentication succeeded; remote payload execution is not observed.",
    },
    {
      ...base,
      id: "JOIN-LAT-05",
      sequence: 14,
      status: "correlated",
      sourceCategory: "deterministic_model",
      sourceLabel: "TRACE correlation",
      timestamp: "2026-08-28T14:05:15Z",
      actor: { kind: "system", id: "trace-correlation-v1" },
      fromEntityId: "identity:svc-fin-reports",
      toEntityId: "secret:ci-deploy-token",
      relation: "read_secret",
      matchField: "principalId",
      matchValue: "svc-fin-reports",
      evidenceIds: ["EVT-CLOUD-0448-08", "EVT-CLOUD-0448-09"],
      label: "Service identity to deployment credential",
      limitation: "The secret read does not prove disclosure or use.",
    },
  ],
  enrichments: [
    {
      ...base,
      id: "ENR-LAT-FILE-01",
      sequence: 15,
      status: "supporting",
      sourceCategory: "static_analysis",
      sourceLabel: "file analysis",
      timestamp: "2026-08-28T14:05:20Z",
      actor: { kind: "system", id: "fixture-file-analysis" },
      entityId: "file:invoice-sync-helper",
      title: "Helper analysis",
      summary:
        "Unsigned, zero prevalence, first seen from a user-writable path, and observed executing.",
      caveat:
        "Stored analysis snapshot only; no binary was uploaded or executed.",
      toolName: "enrich_file",
      payload: {
        kind: "file_context",
        signer: "unsigned",
        prevalence30d: 0,
        screeningVerdict: "suspicious_untrusted_helper",
        containsRestrictedExport: false,
        executionObserved: true,
      },
    },
    {
      ...base,
      id: "ENR-LAT-HASH-04",
      sequence: 33,
      status: "supporting",
      sourceCategory: "static_analysis",
      sourceLabel: "threat intelligence snapshot",
      timestamp: "2026-08-28T14:05:24Z",
      actor: { kind: "system", id: "fixture-hash-intelligence" },
      entityId: "file:invoice-sync-helper",
      title: "File hash intelligence",
      summary:
        "The exact SHA-256 is classified as malicious with high confidence in the archived intelligence snapshot and has zero enterprise prevalence.",
      caveat:
        "Archived hash intelligence only. TRACE did not contact an external reputation service.",
      toolName: "enrich_file",
      payload: {
        kind: "hash_intelligence_fixture",
        sha256:
          "65fb21f3b3b11f7a7d45f31965dad35935e6d9c860ca6f618999510db74260b9",
        verdict: "malicious",
        confidence: "high",
        enterprisePrevalence30d: 0,
        sourceCoverage: "archived_hash_intelligence_only",
      },
    },
    {
      ...base,
      id: "ENR-LAT-ENDPOINT-01",
      sequence: 16,
      status: "supporting",
      sourceCategory: "asset_inventory",
      sourceLabel: "endpoint inventory",
      timestamp: "2026-08-28T14:05:21Z",
      actor: { kind: "system", id: "fixture-endpoint-inventory" },
      entityId: "endpoint:fin-ws-044",
      title: "Endpoint ownership and control",
      summary:
        "FIN-WS-044 belongs to Maya Chen, has healthy EDR, and supports isolation.",
      caveat: "Fixed inventory; not a live EDR query.",
      toolName: "enrich_endpoint",
      payload: {
        kind: "endpoint_posture",
        owner: "Maya Chen",
        edrStatus: "healthy",
        lastSeenAt: "2026-08-28T14:05:18Z",
        isolationSupported: true,
      },
    },
    {
      ...base,
      id: "ENR-LAT-IDENTITY-01",
      sequence: 17,
      status: "supporting",
      sourceCategory: "identity_directory",
      sourceLabel: "service identity baseline",
      timestamp: "2026-08-28T14:05:22Z",
      actor: { kind: "system", id: "fixture-directory" },
      entityId: "identity:svc-fin-reports",
      title: "Service identity scope",
      summary:
        "svc-fin-reports is scoped to FIN-REPORTS-SRV-010 and has no APP-SRV-021 logons in 90 days.",
      caveat: "Fixed directory and configuration snapshot.",
      toolName: "enrich_identity",
      payload: {
        kind: "service_identity_baseline",
        expectedScope: "FIN-REPORTS-SRV-010",
        priorTargetLogons90d: 0,
        credentialAgeDays: 183,
        disableSupported: true,
        rotateSupported: true,
      },
    },
    {
      ...base,
      id: "ENR-LAT-DEST-01",
      sequence: 18,
      status: "disputed",
      sourceCategory: "network_inventory",
      sourceLabel: "destination inventory",
      timestamp: "2026-08-28T14:05:23Z",
      actor: { kind: "system", id: "fixture-network-inventory" },
      entityId: "indicator:203.0.113.91",
      title: "Destination context",
      summary:
        "The address is absent from approved egress and has zero peer history.",
      caveat:
        "The address is reserved for documentation; no ownership or reputation claim is made.",
      toolName: "enrich_network_indicator",
      payload: {
        kind: "destination_context",
        addressClass: "documentation_range",
        inventoryMatch: false,
        priorEndpointConnections30d: 0,
        reputation: "not_applicable_documentation_range",
      },
    },
    {
      ...base,
      id: "ENR-LAT-STATIC-02",
      sequence: 31,
      status: "supporting",
      sourceCategory: "static_analysis",
      sourceLabel: "static-analysis archive",
      timestamp: "2026-08-28T14:05:24Z",
      actor: { kind: "system", id: "fixture-static-analysis" },
      entityId: "file:invoice-sync-helper",
      title: "Static analysis",
      summary:
        "Archived metadata shows an unsigned PE32+ file with network-client and service-control API references.",
      caveat:
        "Archived static analysis only. Static characteristics do not prove execution, intent, or malware family.",
      toolName: "enrich_file",
      payload: {
        kind: "static_analysis_fixture",
        fileFormat: "PE32+",
        signer: "unsigned",
        prevalence30d: 0,
        characteristics: [
          "embedded_sync_profile",
          "network_client_api",
          "service_control_api",
        ],
        analysisCoverage: "deterministic_fixture_summary_only",
      },
    },
    {
      ...base,
      id: "ENR-LAT-SANDBOX-03",
      sequence: 32,
      status: "supporting",
      sourceCategory: "sandbox_artifact",
      sourceLabel: "sandbox behavior archive",
      timestamp: "2026-08-28T14:05:25Z",
      actor: { kind: "system", id: "fixture-sandbox-behavior" },
      entityId: "file:invoice-sync-helper",
      title: "Sandbox behavior",
      summary:
        "An archived sandbox run records temp-path execution, two TLS connections, and remote service-control intent.",
      caveat:
        "No binary was uploaded or executed by TRACE. The remote service start remained blocked in observed endpoint telemetry.",
      toolName: "enrich_file",
      payload: {
        kind: "sandbox_behavior_fixture",
        fixtureRunId: "sandbox-fixture-0448-a",
        profile: "windows_11_enterprise_fixture",
        observedBehaviors: [
          "temp_path_execution",
          "two_tls_connections",
          "remote_service_control_attempt",
        ],
        networkDestination: "203.0.113.91",
        externalExecution: false,
      },
    },
  ],
  investigationQueries: [
    {
      id: "QRY-ENDPOINT-FILE-01",
      title: "Helper behavior and prevalence",
      question:
        "What did the unsigned helper do, and has it appeared elsewhere?",
      objective:
        "Correlate file creation, process lineage, signer state, and peer prevalence before deeper analysis.",
      targetEntityId: "file:invoice-sync-helper",
      toolName: "enrich_file",
      resultArtifactId: "ENR-LAT-FILE-01",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "Endpoint telemetry",
          sourceCategory: "endpoint_telemetry",
          timeRange: {
            start: "2026-07-29T00:00:00Z",
            end: "2026-08-28T14:05:20Z",
          },
          syntheticRecordCount: 2400,
        },
        {
          sourceLabel: "Enterprise file prevalence",
          sourceCategory: "static_analysis",
          timeRange: {
            start: "2026-05-30T00:00:00Z",
            end: "2026-08-28T14:05:20Z",
          },
          syntheticRecordCount: 96,
        },
      ],
      matchedRecordCount: 11,
      returnedRecordCount: 6,
      returnedRecords: [
        returnedRecord(
          "QRR-ENDPOINT-FILE-01",
          "Endpoint telemetry",
          "2026-08-28T14:02:11Z",
          "File creation",
          ["file:invoice-sync-helper", "endpoint:fin-ws-044"],
          {
            File: "invoice-sync-helper.exe",
            Host: "FIN-WS-044",
            Source: "C:\\Users\\mchen\\Downloads",
            SHA256:
              "65fb21f3b3b11f7a7d45f31965dad35935e6d9c860ca6f618999510db74260b9",
            "File size": "418,304 bytes",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-FILE-02",
          "Endpoint telemetry",
          "2026-08-28T14:02:18Z",
          "Process start",
          ["file:invoice-sync-helper", "endpoint:fin-ws-044"],
          {
            Process: "invoice-sync-helper.exe",
            Parent: "explorer.exe",
            Signer: "Unsigned",
            "Process GUID": "PG-0448-A",
            Integrity: "Medium",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-FILE-03",
          "Endpoint telemetry",
          "2026-08-28T14:03:12Z",
          "TLS connection",
          [
            "file:invoice-sync-helper",
            "endpoint:fin-ws-044",
            "indicator:203.0.113.91",
          ],
          {
            Destination: "203.0.113.91:443",
            Protocol: "TLS",
            Process: "invoice-sync-helper.exe",
            "Process GUID": "PG-0448-A",
            "Bytes sent": "4,816",
            "Bytes received": "1,024",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-FILE-04",
          "Endpoint telemetry",
          "2026-08-28T14:04:12Z",
          "TLS connection",
          [
            "file:invoice-sync-helper",
            "endpoint:fin-ws-044",
            "indicator:203.0.113.91",
          ],
          {
            Destination: "203.0.113.91:443",
            Interval: "60 seconds",
            Process: "invoice-sync-helper.exe",
            "Process GUID": "PG-0448-A",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-FILE-05",
          "Enterprise file prevalence",
          "2026-08-28T14:05:20Z",
          "Prevalence record",
          ["file:invoice-sync-helper"],
          {
            SHA256:
              "65fb21f3b3b11f7a7d45f31965dad35935e6d9c860ca6f618999510db74260b9",
            "Peer prevalence": "0 in 30 days",
            Signer: "Unsigned",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-FILE-06",
          "Endpoint telemetry",
          "2026-08-28T14:05:20Z",
          "Execution lineage",
          ["file:invoice-sync-helper", "endpoint:fin-ws-044"],
          { User: "Maya Chen", Path: "User-writable", Outcome: "Observed" },
        ),
      ],
      resultChange:
        "Unsigned, zero-prevalence execution from a user-writable path raises the containment case.",
      caveat: "No real binary was uploaded, executed, or detonated.",
    },
    {
      id: "QRY-ENDPOINT-HASH-10",
      title: "File hash intelligence",
      question:
        "What does archived threat intelligence report for the exact SHA-256?",
      objective:
        "Check the immutable sample hash against the archived intelligence snapshot and enterprise prevalence without making an external request.",
      targetEntityId: "file:invoice-sync-helper",
      toolName: "enrich_file",
      resultArtifactId: "ENR-LAT-HASH-04",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "Threat intelligence snapshot",
          sourceCategory: "static_analysis",
          timeRange: {
            start: "2026-05-30T00:00:00Z",
            end: "2026-08-28T14:05:24Z",
          },
          syntheticRecordCount: 412,
        },
        {
          sourceLabel: "Enterprise file prevalence",
          sourceCategory: "endpoint_telemetry",
          timeRange: {
            start: "2026-07-29T00:00:00Z",
            end: "2026-08-28T14:05:24Z",
          },
          syntheticRecordCount: 84,
        },
      ],
      matchedRecordCount: 3,
      returnedRecordCount: 3,
      returnedRecords: [
        returnedRecord(
          "QRR-ENDPOINT-HASH-01",
          "Threat intelligence snapshot",
          "2026-08-28T14:05:24Z",
          "Exact hash match",
          ["file:invoice-sync-helper"],
          {
            SHA256:
              "65fb21f3b3b11f7a7d45f31965dad35935e6d9c860ca6f618999510db74260b9",
            Verdict: "Malicious",
            Confidence: "High",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-HASH-02",
          "Threat intelligence snapshot",
          "2026-08-28T14:05:24Z",
          "Behavior classification",
          ["file:invoice-sync-helper"],
          {
            "Threat type": "Remote service execution helper",
            "First cataloged": "2026-08-12T18:22:09Z",
            Coverage: "Archived intelligence",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-HASH-03",
          "Enterprise file prevalence",
          "2026-08-28T14:05:24Z",
          "Enterprise prevalence",
          ["file:invoice-sync-helper"],
          {
            SHA256:
              "65fb21f3b3b11f7a7d45f31965dad35935e6d9c860ca6f618999510db74260b9",
            Devices: "0 in 30 days",
            "Prior execution": "None observed",
          },
        ),
      ],
      resultChange:
        "The exact file hash is classified as malicious with high confidence and has zero enterprise prevalence.",
      caveat:
        "This result uses an archived intelligence snapshot; no external OSINT provider was contacted.",
    },
    {
      id: "QRY-ENDPOINT-STATIC-08",
      title: "Static file analysis",
      question: "Which static characteristics warrant follow-up?",
      objective:
        "Attach an archived file-format and API-reference summary without exposing executable content.",
      targetEntityId: "file:invoice-sync-helper",
      toolName: "enrich_file",
      resultArtifactId: "ENR-LAT-STATIC-02",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "static-analysis archive",
          sourceCategory: "static_analysis",
          timeRange: {
            start: "2026-08-28T14:05:20Z",
            end: "2026-08-28T14:05:24Z",
          },
          syntheticRecordCount: 14,
        },
      ],
      matchedRecordCount: 3,
      returnedRecordCount: 3,
      returnedRecords: [
        returnedRecord(
          "QRR-ENDPOINT-STATIC-01",
          "static-analysis archive",
          "2026-08-28T14:05:24Z",
          "PE header",
          ["file:invoice-sync-helper"],
          { Format: "PE32+", Architecture: "x64", Signer: "Unsigned" },
        ),
        returnedRecord(
          "QRR-ENDPOINT-STATIC-02",
          "static-analysis archive",
          "2026-08-28T14:05:24Z",
          "Import summary",
          ["file:invoice-sync-helper"],
          {
            Import: "WinHTTP",
            Meaning: "Network-client API",
            Coverage: "Archive summary",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-STATIC-03",
          "static-analysis archive",
          "2026-08-28T14:05:24Z",
          "Import summary",
          ["file:invoice-sync-helper"],
          {
            Import: "OpenSCManager",
            Meaning: "Service-control API",
            Coverage: "Archive summary",
          },
        ),
      ],
      resultChange:
        "Unsigned PE metadata and network-client and service-control references support deeper behavior review.",
      caveat:
        "This is an archived summary, not raw disassembly or a live IDA or Ghidra session.",
    },
    {
      id: "QRY-ENDPOINT-SANDBOX-09",
      title: "Review sandbox behavior",
      question: "Which behaviors were recorded in the archived sandbox run?",
      objective:
        "Attach an archived behavior summary and preserve the boundary between sandbox analysis and observed telemetry.",
      targetEntityId: "file:invoice-sync-helper",
      toolName: "enrich_file",
      resultArtifactId: "ENR-LAT-SANDBOX-03",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "sandbox behavior archive",
          sourceCategory: "sandbox_artifact",
          timeRange: {
            start: "2026-08-28T14:05:20Z",
            end: "2026-08-28T14:05:25Z",
          },
          syntheticRecordCount: 8,
        },
      ],
      matchedRecordCount: 3,
      returnedRecordCount: 3,
      returnedRecords: [
        returnedRecord(
          "QRR-ENDPOINT-SANDBOX-01",
          "sandbox behavior archive",
          "2026-08-28T14:05:25Z",
          "Sandbox execution",
          ["file:invoice-sync-helper"],
          {
            Profile: "Windows 11 Enterprise",
            Path: "Temp directory",
            External: "No",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-SANDBOX-02",
          "sandbox behavior archive",
          "2026-08-28T14:05:25Z",
          "Sandbox network",
          ["file:invoice-sync-helper", "indicator:203.0.113.91"],
          {
            Destination: "203.0.113.91:443",
            Connections: "2 TLS",
            External: "No",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-SANDBOX-03",
          "sandbox behavior archive",
          "2026-08-28T14:05:25Z",
          "Sandbox service control",
          ["file:invoice-sync-helper", "endpoint:app-srv-021"],
          {
            Intent: "Remote service control",
            Observed: "Archived behavior",
            Outcome: "No external execution",
          },
        ),
      ],
      resultChange:
        "Archived sandbox behavior aligns with the observed temp execution, repeated TLS, and blocked service-control attempt.",
      caveat:
        "No binary was uploaded or executed by TRACE; only existing EDR events establish observed behavior.",
    },
    {
      id: "QRY-ENDPOINT-HOST-02",
      title: "Endpoint ownership and control",
      question: "Can FIN-WS-044 be isolated without losing collection?",
      objective:
        "Resolve ownership, EDR health, last contact, and supported containment controls.",
      targetEntityId: "endpoint:fin-ws-044",
      toolName: "enrich_endpoint",
      resultArtifactId: "ENR-LAT-ENDPOINT-01",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "EDR device inventory",
          sourceCategory: "asset_inventory",
          timeRange: {
            start: "2026-08-21T00:00:00Z",
            end: "2026-08-28T14:05:21Z",
          },
          syntheticRecordCount: 320,
        },
        {
          sourceLabel: "EDR sensor health",
          sourceCategory: "endpoint_telemetry",
          timeRange: {
            start: "2026-08-28T13:05:00Z",
            end: "2026-08-28T14:05:21Z",
          },
          syntheticRecordCount: 680,
        },
      ],
      matchedRecordCount: 8,
      returnedRecordCount: 4,
      returnedRecords: [
        returnedRecord(
          "QRR-ENDPOINT-HOST-01",
          "EDR device inventory",
          "2026-08-28T14:05:18Z",
          "Device inventory",
          ["endpoint:fin-ws-044"],
          { Host: "FIN-WS-044", Owner: "Maya Chen", Criticality: "Standard" },
        ),
        returnedRecord(
          "QRR-ENDPOINT-HOST-02",
          "EDR sensor health",
          "2026-08-28T14:05:18Z",
          "EDR heartbeat",
          ["endpoint:fin-ws-044"],
          { Host: "FIN-WS-044", Status: "Healthy", "Last seen": "14:05:18Z" },
        ),
        returnedRecord(
          "QRR-ENDPOINT-HOST-03",
          "EDR device inventory",
          "2026-08-28T14:05:21Z",
          "Containment capability",
          ["endpoint:fin-ws-044"],
          {
            Isolation: "Supported",
            Collection: "Retained",
            Approval: "Required",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-HOST-04",
          "EDR sensor health",
          "2026-08-28T14:05:21Z",
          "Response posture",
          ["endpoint:fin-ws-044"],
          { Host: "FIN-WS-044", Sensor: "Connected", Response: "Ready" },
        ),
      ],
      resultChange:
        "Healthy EDR and supported isolation make FIN-WS-044 response-ready.",
      caveat: "Fixed inventory; no live endpoint was queried.",
    },
    {
      id: "QRY-ENDPOINT-IDENTITY-03",
      title: "Service identity scope deviation",
      question:
        "Is svc-fin-reports operating outside its normal host boundary?",
      objective:
        "Compare Windows logons, expected service scope, credential age, and prior target history.",
      targetEntityId: "identity:svc-fin-reports",
      toolName: "enrich_identity",
      resultArtifactId: "ENR-LAT-IDENTITY-01",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "Windows authentication",
          sourceCategory: "windows_authentication",
          timeRange: {
            start: "2026-05-30T00:00:00Z",
            end: "2026-08-28T14:05:22Z",
          },
          syntheticRecordCount: 1840,
        },
        {
          sourceLabel: "service identity directory",
          sourceCategory: "identity_directory",
          timeRange: {
            start: "2026-05-30T00:00:00Z",
            end: "2026-08-28T14:05:22Z",
          },
          syntheticRecordCount: 160,
        },
      ],
      matchedRecordCount: 6,
      returnedRecordCount: 3,
      returnedRecords: [
        returnedRecord(
          "QRR-ENDPOINT-IDENTITY-01",
          "Windows authentication",
          "2026-08-28T14:05:12Z",
          "Network logon",
          [
            "identity:svc-fin-reports",
            "endpoint:fin-ws-044",
            "endpoint:app-srv-021",
          ],
          {
            Account: "svc-fin-reports",
            Source: "FIN-WS-044",
            Target: "APP-SRV-021",
            "Event ID": "4624",
            "Logon type": "3",
            "Authentication package": "Kerberos",
            "Logon ID": "0xA0448",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-IDENTITY-02",
          "service identity directory",
          "2026-08-28T14:05:22Z",
          "Service scope",
          ["identity:svc-fin-reports"],
          {
            Account: "svc-fin-reports",
            "Expected host": "FIN-REPORTS-SRV-010",
            "Credential age": "183 days",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-IDENTITY-03",
          "Windows authentication",
          "2026-08-28T14:05:22Z",
          "Target history",
          ["identity:svc-fin-reports", "endpoint:app-srv-021"],
          {
            Target: "APP-SRV-021",
            "Prior logons": "0 in 90 days",
            Result: "Outside expected scope",
          },
        ),
      ],
      resultChange:
        "APP-SRV-021 is outside the expected scope and has zero prior logons in 90 days.",
      caveat: "The baseline is a bounded deterministic identity snapshot.",
    },
    {
      id: "QRY-ENDPOINT-EGRESS-04",
      title: "Repeated destination context",
      question:
        "Is the TLS destination known, approved, or previously observed?",
      objective:
        "Resolve the destination against approved egress and 30-day endpoint peer history.",
      targetEntityId: "indicator:203.0.113.91",
      toolName: "enrich_network_indicator",
      resultArtifactId: "ENR-LAT-DEST-01",
      requiresStageId: null,
      sourceScopes: [
        {
          sourceLabel: "Network telemetry",
          sourceCategory: "endpoint_telemetry",
          timeRange: {
            start: "2026-07-29T00:00:00Z",
            end: "2026-08-28T14:05:23Z",
          },
          syntheticRecordCount: 2860,
        },
        {
          sourceLabel: "approved-egress inventory",
          sourceCategory: "network_inventory",
          timeRange: {
            start: "2026-08-01T00:00:00Z",
            end: "2026-08-28T14:05:23Z",
          },
          syntheticRecordCount: 112,
        },
      ],
      matchedRecordCount: 4,
      returnedRecordCount: 4,
      returnedRecords: [
        returnedRecord(
          "QRR-ENDPOINT-EGRESS-01",
          "Network telemetry",
          "2026-08-28T14:03:12Z",
          "TLS connection",
          ["endpoint:fin-ws-044", "indicator:203.0.113.91"],
          {
            Source: "FIN-WS-044",
            Destination: "203.0.113.91:443",
            Protocol: "TLS",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-EGRESS-02",
          "Network telemetry",
          "2026-08-28T14:04:12Z",
          "Repeated connection",
          ["endpoint:fin-ws-044", "indicator:203.0.113.91"],
          {
            Source: "FIN-WS-044",
            Destination: "203.0.113.91:443",
            Interval: "60 seconds",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-EGRESS-03",
          "approved-egress inventory",
          "2026-08-28T14:05:23Z",
          "Egress inventory",
          ["indicator:203.0.113.91"],
          {
            Destination: "203.0.113.91",
            Match: "No approved egress",
            Address: "Documentation range",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-EGRESS-04",
          "Network telemetry",
          "2026-08-28T14:05:23Z",
          "Peer history",
          ["endpoint:fin-ws-044", "indicator:203.0.113.91"],
          {
            Host: "FIN-WS-044",
            "Prior peers": "0 in 30 days",
            Result: "New destination",
          },
        ),
      ],
      resultChange:
        "No approved-egress match and no prior FIN-WS-044 peer history were found.",
      caveat:
        "The address is documentation-range data; reputation is not asserted.",
    },
    {
      id: "QRY-ENDPOINT-APP-05",
      title: "Target execution verification",
      question: "Did APP-SRV-021 execute the attempted remote service payload?",
      objective:
        "Reconcile the remote-service attempt with target prevention and EDR health.",
      targetEntityId: "endpoint:app-srv-021",
      toolName: "enrich_endpoint",
      resultArtifactId: "ENR-LAT-APP-01",
      requiresStageId: "STREAM-LAT-01",
      sourceScopes: [
        {
          sourceLabel: "application-host telemetry",
          sourceCategory: "endpoint_telemetry",
          timeRange: {
            start: "2026-08-28T13:50:00Z",
            end: "2026-08-28T14:05:20Z",
          },
          syntheticRecordCount: 248,
        },
        {
          sourceLabel: "application-host posture",
          sourceCategory: "cloud_configuration",
          timeRange: {
            start: "2026-08-21T00:00:00Z",
            end: "2026-08-28T14:05:20Z",
          },
          syntheticRecordCount: 52,
        },
      ],
      matchedRecordCount: 9,
      returnedRecordCount: 5,
      returnedRecords: [
        returnedRecord(
          "QRR-ENDPOINT-APP-01",
          "application-host telemetry",
          "2026-08-28T14:05:12Z",
          "Network logon",
          ["identity:svc-fin-reports", "endpoint:app-srv-021"],
          {
            Account: "svc-fin-reports",
            Target: "APP-SRV-021",
            Outcome: "Success",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-APP-02",
          "application-host telemetry",
          "2026-08-28T14:05:14Z",
          "Service start attempt",
          ["file:invoice-sync-helper", "endpoint:app-srv-021"],
          {
            Target: "APP-SRV-021",
            Outcome: "Blocked before execution",
            Process: "invoice-sync-helper.exe",
            "Detection ID": "DET-REMOTE-SVC-207",
            "Prevention rule": "Remote service creation",
            "Target process": "Not created",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-APP-03",
          "application-host posture",
          "2026-08-28T14:05:20Z",
          "EDR posture",
          ["endpoint:app-srv-021"],
          { Host: "APP-SRV-021", Status: "Healthy", Collection: "Available" },
        ),
        returnedRecord(
          "QRR-ENDPOINT-APP-04",
          "application-host telemetry",
          "2026-08-28T14:05:20Z",
          "Process review",
          ["endpoint:app-srv-021"],
          {
            Host: "APP-SRV-021",
            Payload: "Not observed",
            Result: "No execution evidence",
            "Process review": "No matching process GUID or image load",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-APP-05",
          "application-host posture",
          "2026-08-28T14:05:20Z",
          "Containment capability",
          ["endpoint:app-srv-021"],
          {
            Host: "APP-SRV-021",
            Isolation: "Supported",
            Response: "Not required",
          },
        ),
      ],
      resultChange:
        "Authentication occurred, but the remote service start was prevented before execution.",
      caveat: "No compromise of APP-SRV-021 is asserted by this result.",
    },
    {
      id: "QRY-ENDPOINT-SECRET-06",
      title: "Credential reach and rotation scope",
      question:
        "What can ci/deploy/production authorize, and can it be rotated?",
      objective:
        "Resolve secret age, downstream permission, and supported rotation scope.",
      targetEntityId: "secret:ci-deploy-token",
      toolName: "enrich_resource",
      resultArtifactId: "ENR-LAT-SECRET-01",
      requiresStageId: "STREAM-LAT-02",
      sourceScopes: [
        {
          sourceLabel: "secret policy graph",
          sourceCategory: "cloud_configuration",
          timeRange: {
            start: "2026-05-30T00:00:00Z",
            end: "2026-08-28T14:06:16Z",
          },
          syntheticRecordCount: 184,
        },
        {
          sourceLabel: "Cloud audit",
          sourceCategory: "cloud_audit",
          timeRange: {
            start: "2026-07-29T00:00:00Z",
            end: "2026-08-28T14:06:16Z",
          },
          syntheticRecordCount: 640,
        },
      ],
      matchedRecordCount: 8,
      returnedRecordCount: 4,
      returnedRecords: [
        returnedRecord(
          "QRR-ENDPOINT-SECRET-01",
          "secret policy graph",
          "2026-08-28T14:06:16Z",
          "Secret policy",
          ["secret:ci-deploy-token"],
          {
            Secret: "ci/deploy/production",
            Permission: "Deploy billing-api",
            Rotation: "Supported",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-SECRET-02",
          "Cloud audit",
          "2026-08-28T14:05:13Z",
          "Credential read",
          ["identity:svc-fin-reports", "secret:ci-deploy-token"],
          {
            Principal: "svc-fin-reports",
            Secret: "ci/deploy/production",
            Outcome: "Success",
            Event: "GetSecretValue",
            "Request ID": "req-0448-8f21",
            Source: "FIN-WS-044",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-SECRET-03",
          "secret policy graph",
          "2026-08-28T14:06:16Z",
          "Credential age",
          ["secret:ci-deploy-token"],
          {
            Secret: "ci/deploy/production",
            Age: "183 days",
            Classification: "Production deployment credential",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-SECRET-04",
          "Cloud audit",
          "2026-08-28T14:06:16Z",
          "Deployment activity",
          ["secret:ci-deploy-token", "workload:billing-api"],
          {
            Workload: "billing-api",
            Deployment: "Not observed",
            Scope: "No workload change",
          },
        ),
      ],
      resultChange:
        "The 183-day credential can deploy only billing-api and supports rotation.",
      caveat: "No credential material is included or returned.",
    },
    {
      id: "QRY-ENDPOINT-WORKLOAD-07",
      title: "Known-good recovery point",
      question: "Which approved billing-api image can restore the workload?",
      objective:
        "Compare the current deployment image with the known-good recovery inventory.",
      targetEntityId: "workload:billing-api",
      toolName: "enrich_resource",
      resultArtifactId: "ENR-LAT-WORKLOAD-01",
      requiresStageId: "STREAM-LAT-02",
      sourceScopes: [
        {
          sourceLabel: "deployment inventory",
          sourceCategory: "asset_inventory",
          timeRange: {
            start: "2026-08-21T00:00:00Z",
            end: "2026-08-28T14:06:17Z",
          },
          syntheticRecordCount: 482,
        },
        {
          sourceLabel: "deployment audit history",
          sourceCategory: "cloud_audit",
          timeRange: {
            start: "2026-07-29T00:00:00Z",
            end: "2026-08-28T14:06:17Z",
          },
          syntheticRecordCount: 180,
        },
      ],
      matchedRecordCount: 6,
      returnedRecordCount: 3,
      returnedRecords: [
        returnedRecord(
          "QRR-ENDPOINT-WORKLOAD-01",
          "deployment inventory",
          "2026-08-28T14:06:17Z",
          "Current image",
          ["workload:billing-api"],
          {
            Workload: "billing-api",
            Image: "billing-api:v2026.08.28.3",
            Environment: "Production",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-WORKLOAD-02",
          "deployment inventory",
          "2026-08-28T14:06:17Z",
          "Known-good image",
          ["workload:billing-api"],
          {
            Workload: "billing-api",
            Image: "billing-api:v2026.08.27.7",
            Status: "Known good",
          },
        ),
        returnedRecord(
          "QRR-ENDPOINT-WORKLOAD-03",
          "deployment audit history",
          "2026-08-28T14:06:17Z",
          "Recovery capability",
          ["workload:billing-api"],
          {
            Workload: "billing-api",
            Redeploy: "Supported",
            Execution: "Requires analyst approval",
          },
        ),
      ],
      resultChange:
        "billing-api:v2026.08.27.7 is the approved known-good recovery point.",
      caveat:
        "No malicious deployment is observed and no workload is modified.",
    },
  ],
  tier1Escalation: {
    ...base,
    id: "T1-ESC-ENDPOINT-0448",
    sequence: 19,
    status: "correlated",
    sourceCategory: "deterministic_model",
    sourceLabel: "Tier 1 triage",
    timestamp: "2026-08-28T14:05:15Z",
    actor: { kind: "tier1_ai", id: "tier1-triage-01" },
    confidence: "medium",
    escalationReason:
      "An unsigned helper executed on FIN-WS-044 and repeated TLS egress. The same host showed an out-of-scope service-identity logon to APP-SRV-021 and a production credential read.",
    evidenceIds: [
      "EVT-EDR-0448-01",
      "EVT-EDR-0448-03",
      "EVT-AUTH-0448-05",
      "EVT-EDR-0448-07",
      "EVT-CLOUD-0448-08",
    ],
    observations: [
      {
        id: "T1-OBS-ENDPOINT-EXECUTION",
        status: "observed",
        title: "Unsigned helper executed with repeated egress",
        summary:
          "invoice-sync-helper.exe ran on FIN-WS-044 and made two TLS connections to the same destination 60 seconds apart.",
        entityIds: [
          "file:invoice-sync-helper",
          "endpoint:fin-ws-044",
          "indicator:203.0.113.91",
        ],
        evidenceIds: ["EVT-EDR-0448-01", "EVT-EDR-0448-03", "EVT-EDR-0448-04"],
      },
      {
        id: "T1-OBS-ENDPOINT-LATERAL",
        status: "correlated",
        title: "Service identity crossed its host boundary",
        summary:
          "svc-fin-reports authenticated from FIN-WS-044 to APP-SRV-021 before the helper queried the remote service controller.",
        entityIds: [
          "endpoint:fin-ws-044",
          "identity:svc-fin-reports",
          "endpoint:app-srv-021",
        ],
        evidenceIds: ["EVT-AUTH-0448-05", "EVT-EDR-0448-07"],
      },
      {
        id: "T1-OBS-ENDPOINT-CREDENTIAL",
        status: "observed",
        title: "Production deployment credential was read",
        summary:
          "svc-fin-reports read ci/deploy/production; no deployment action is observed in the initial telemetry.",
        entityIds: ["identity:svc-fin-reports", "secret:ci-deploy-token"],
        evidenceIds: ["EVT-CLOUD-0448-08", "EVT-CLOUD-0448-09"],
      },
    ],
    recommendedSteps: [
      {
        id: "T1-STEP-ENDPOINT-FILE",
        status: "proposed",
        label: "Assess the helper",
        objective:
          "Attach file analysis before deciding whether the helper meets the containment threshold.",
        recommendedTool: "enrich_file",
        entityId: "file:invoice-sync-helper",
        evidenceIds: ["EVT-EDR-0448-01"],
        completionArtifactId: "ENR-LAT-FILE-01",
        investigationQueryId: "QRY-ENDPOINT-FILE-01",
      },
      {
        id: "T1-STEP-ENDPOINT-HASH",
        status: "proposed",
        label: "Check the exact file hash",
        objective:
          "Compare the immutable SHA-256 with bounded threat intelligence and enterprise prevalence before disposition.",
        recommendedTool: "enrich_file",
        entityId: "file:invoice-sync-helper",
        evidenceIds: ["EVT-EDR-0448-01"],
        completionArtifactId: "ENR-LAT-HASH-04",
        investigationQueryId: "QRY-ENDPOINT-HASH-10",
      },
      {
        id: "T1-STEP-ENDPOINT-HOST",
        status: "proposed",
        label: "Verify host containment readiness",
        objective:
          "Attach FIN-WS-044 posture and isolation support while preserving the observed evidence.",
        recommendedTool: "enrich_endpoint",
        entityId: "endpoint:fin-ws-044",
        evidenceIds: ["EVT-EDR-0448-01", "EVT-EDR-0448-03", "EVT-EDR-0448-04"],
        completionArtifactId: "ENR-LAT-ENDPOINT-01",
        investigationQueryId: "QRY-ENDPOINT-HOST-02",
      },
      {
        id: "T1-STEP-ENDPOINT-IDENTITY",
        status: "proposed",
        label: "Verify service-identity scope",
        objective:
          "Attach the svc-fin-reports baseline before inferring unauthorized lateral use.",
        recommendedTool: "enrich_identity",
        entityId: "identity:svc-fin-reports",
        evidenceIds: ["EVT-AUTH-0448-05", "EVT-CLOUD-0448-08"],
        completionArtifactId: "ENR-LAT-IDENTITY-01",
        investigationQueryId: "QRY-ENDPOINT-IDENTITY-03",
      },
      {
        id: "T1-STEP-ENDPOINT-EGRESS",
        status: "proposed",
        label: "Check the repeated destination",
        objective:
          "Attach destination context without claiming ownership or reputation for the documentation address.",
        recommendedTool: "enrich_network_indicator",
        entityId: "indicator:203.0.113.91",
        evidenceIds: ["EVT-EDR-0448-03", "EVT-EDR-0448-04"],
        completionArtifactId: "ENR-LAT-DEST-01",
        investigationQueryId: "QRY-ENDPOINT-EGRESS-04",
      },
    ],
    checksCompleted: [
      "Process and device continuity",
      "Repeated destination correlation",
      "Service identity scope comparison",
      "Application-host and cloud principal continuity",
    ],
    unresolvedQuestions: [
      "Did remote service execution begin on APP-SRV-021?",
      "Which modeled risk segments remain available through svc-fin-reports?",
      "Which controls can halt propagation without erasing evidence?",
    ],
    actionsWithheld: [
      "No endpoint collection or isolation",
      "No egress block",
      "No identity disablement",
      "No credential rotation or workload redeploy",
    ],
  },
  decision: {
    ...base,
    id: "DEC-LAT-01",
    sequence: 20,
    status: "disputed",
    sourceCategory: "analyst_judgment",
    sourceLabel: "Analyst decision",
    timestamp: "2026-08-28T14:05:24Z",
    actor: { kind: "analyst", id: "analyst-01" },
    question: "Does the correlated activity meet the containment threshold?",
    options: [
      {
        id: "confirmed_malicious",
        label: "Confirm malicious · contain",
        rationale:
          "Unsigned execution, two TLS connections 60 seconds apart, out-of-scope authentication, a blocked remote service-start attempt, and a production credential read meet the containment threshold.",
      },
      {
        id: "insufficient_evidence",
        label: "Evidence insufficient",
        rationale:
          "The observed events do not yet justify a containment classification.",
      },
    ],
    requiresEnrichmentIds: [
      "ENR-LAT-FILE-01",
      "ENR-LAT-HASH-04",
      "ENR-LAT-ENDPOINT-01",
      "ENR-LAT-IDENTITY-01",
      "ENR-LAT-APP-01",
    ],
    evidenceIds: [
      "EVT-EDR-0448-01",
      "EVT-EDR-0448-03",
      "EVT-AUTH-0448-05",
      "EVT-EDR-0448-07",
      "EVT-CLOUD-0448-08",
      "EVT-EDR-0448-10",
    ],
    effect: "Records the case disposition. It does not execute containment.",
  },
  reachability: {
    ...base,
    id: "MODEL-LAT-REACH-01",
    sequence: 21,
    status: "modeled",
    sourceCategory: "deterministic_model",
    sourceLabel: "Graph reachability model v1",
    timestamp: "2026-08-28T14:05:25Z",
    actor: { kind: "system", id: "graph-reachability-v1" },
    model: "graph_reachability_v1",
    sourceEntityId: "endpoint:fin-ws-044",
    assumption:
      "The service identity scope and deployment credential remain valid until an approved simulated control severs them.",
    reachableEntityIds: [
      "endpoint:app-srv-021",
      "secret:ci-deploy-token",
      "workload:billing-api",
    ],
    paths: [
      {
        id: "PATH-LAT-EGRESS",
        entityIds: ["endpoint:fin-ws-044", "indicator:203.0.113.91"],
      },
      {
        id: "PATH-LAT-01",
        entityIds: ["endpoint:fin-ws-044", "identity:svc-fin-reports"],
      },
      {
        id: "PATH-LAT-02",
        entityIds: ["identity:svc-fin-reports", "endpoint:app-srv-021"],
      },
      {
        id: "PATH-LAT-03",
        entityIds: ["identity:svc-fin-reports", "secret:ci-deploy-token"],
      },
      {
        id: "PATH-LAT-04",
        entityIds: ["secret:ci-deploy-token", "workload:billing-api"],
      },
    ],
    caveat:
      "Reachable means permitted in the fixture model, not accessed or compromised.",
  },
  counterfactual: {
    ...base,
    id: "MODEL-LAT-CF-01",
    sequence: 22,
    status: "simulated",
    sourceCategory: "deterministic_model",
    sourceLabel: "Control simulation v1",
    timestamp: "2026-08-28T14:05:26Z",
    actor: { kind: "system", id: "control-simulation-v1" },
    control: "isolate_compromised_path",
    changedEntityId: "endpoint:fin-ws-044",
    severedPathIds: ["PATH-LAT-EGRESS", "PATH-LAT-01"],
    remainingPathIds: ["PATH-LAT-02", "PATH-LAT-03", "PATH-LAT-04"],
    caveat:
      "The model does not contact an endpoint, directory, secret store, or deployment system.",
  },
  stream: {
    mode: "deterministic_manual_replay",
    stages: [
      {
        id: "STREAM-LAT-01",
        ordinal: 1,
        title: "Remote service start blocked",
        summary:
          "EDR confirmed that APP-SRV-021 blocked the remote service-start attempt before execution.",
        receivedAt: "2026-08-28T14:05:18Z",
        entities: [],
        events: [
          {
            ...base,
            id: "EVT-EDR-0448-10",
            sequence: 23,
            status: "observed",
            sourceCategory: "endpoint_telemetry",
            sourceLabel: "EDR stream",
            timestamp: "2026-08-28T14:05:18Z",
            actor: { kind: "source_system", id: "fixture-edr-stream" },
            action: "RemoteServiceAttempt",
            entityIds: [
              "endpoint:fin-ws-044",
              "identity:svc-fin-reports",
              "endpoint:app-srv-021",
            ],
            summary:
              "APP-SRV-021 blocked the remote service-start attempt before service execution.",
            payload: {
              kind: "edr_remote_service_attempt",
              sourceHostname: "FIN-WS-044",
              targetHostname: "APP-SRV-021",
              processName: "sc.exe",
              commandLineDisplay:
                "sc.exe \\\\APP-SRV-021 create InvoiceSyncUpdater binPath= <synthetic-redacted>",
              outcome: "BLOCKED_BEFORE_EXECUTION",
            },
          },
        ],
        joins: [
          {
            ...base,
            id: "JOIN-LAT-06",
            sequence: 24,
            status: "correlated",
            sourceCategory: "deterministic_model",
            sourceLabel: "TRACE correlation",
            timestamp: "2026-08-28T14:05:19Z",
            actor: { kind: "system", id: "trace-correlation-v1" },
            fromEntityId: "endpoint:fin-ws-044",
            toEntityId: "endpoint:app-srv-021",
            relation: "attempted_remote_service_control",
            matchField: "sourceHostname + targetHostname + logonId",
            matchValue: "FIN-WS-044 + APP-SRV-021 + 0xA0448",
            evidenceIds: [
              "EVT-AUTH-0448-05",
              "EVT-EDR-0448-07",
              "EVT-EDR-0448-10",
            ],
            label: "Remote service attempt blocked before execution",
            limitation:
              "The target accepted authentication but did not execute the service payload.",
          },
        ],
        enrichments: [
          {
            ...base,
            id: "ENR-LAT-APP-01",
            sequence: 25,
            status: "supporting",
            sourceCategory: "cloud_configuration",
            sourceLabel: "application-host posture",
            timestamp: "2026-08-28T14:05:20Z",
            actor: { kind: "system", id: "fixture-app-posture" },
            entityId: "endpoint:app-srv-021",
            title: "Application-host posture",
            summary:
              "APP-SRV-021 blocked remote service execution and remains visible to healthy EDR.",
            caveat: "Fixed fixture posture; no live host was queried.",
            toolName: "enrich_endpoint",
            payload: {
              kind: "endpoint_posture",
              owner: "Billing Platform",
              edrStatus: "healthy",
              lastSeenAt: "2026-08-28T14:05:18Z",
              isolationSupported: true,
            },
          },
        ],
        responseActionIds: [
          "collect_endpoint_forensics",
          "contain_endpoint",
          "block_network_indicator",
          "disable_service_identity",
        ],
      },
      {
        id: "STREAM-LAT-02",
        ordinal: 2,
        title: "Recovery scope confirmed",
        summary:
          "Deployment inventory exposed the current and known-good billing-api images for synthetic recovery planning.",
        receivedAt: "2026-08-28T14:06:09Z",
        entities: [],
        events: [
          {
            ...base,
            id: "EVT-CLOUD-0448-11",
            sequence: 26,
            status: "observed",
            sourceCategory: "cloud_audit",
            sourceLabel: "deployment inventory",
            timestamp: "2026-08-28T14:06:09Z",
            actor: {
              kind: "source_system",
              id: "fixture-deployment-inventory",
            },
            action: "ReadWorkloadImage",
            entityIds: ["secret:ci-deploy-token", "workload:billing-api"],
            summary:
              "billing-api currently references billing-api:v2026.08.28.3.",
            payload: {
              kind: "cloud_workload_inventory",
              workloadId: "billing-api",
              currentImage: "billing-api:v2026.08.28.3",
              knownGoodImage: "billing-api:v2026.08.27.7",
              outcome: "OBSERVED",
            },
          },
          {
            ...base,
            id: "EVT-CLOUD-0448-12",
            sequence: 27,
            status: "observed",
            sourceCategory: "cloud_audit",
            sourceLabel: "deployment history",
            timestamp: "2026-08-28T14:06:14Z",
            actor: { kind: "source_system", id: "fixture-deployment-history" },
            action: "ReadKnownGoodImage",
            entityIds: ["workload:billing-api"],
            summary:
              "Deployment history identifies billing-api:v2026.08.27.7 as known good.",
            payload: {
              kind: "cloud_workload_inventory",
              workloadId: "billing-api",
              currentImage: "billing-api:v2026.08.28.3",
              knownGoodImage: "billing-api:v2026.08.27.7",
              outcome: "OBSERVED",
            },
          },
        ],
        joins: [
          {
            ...base,
            id: "JOIN-LAT-07",
            sequence: 28,
            status: "correlated",
            sourceCategory: "deterministic_model",
            sourceLabel: "TRACE correlation",
            timestamp: "2026-08-28T14:06:15Z",
            actor: { kind: "system", id: "trace-correlation-v1" },
            fromEntityId: "secret:ci-deploy-token",
            toEntityId: "workload:billing-api",
            relation: "authorizes_deployment_to",
            matchField: "deploymentPolicy + workloadId",
            matchValue: "ci-deploy-production + billing-api",
            evidenceIds: ["EVT-CLOUD-0448-08", "EVT-CLOUD-0448-11"],
            label: "Deployment credential to production workload",
            limitation:
              "The path is permission context; no deployment was observed.",
          },
        ],
        enrichments: [
          {
            ...base,
            id: "ENR-LAT-SECRET-01",
            sequence: 29,
            status: "supporting",
            sourceCategory: "cloud_configuration",
            sourceLabel: "secret posture",
            timestamp: "2026-08-28T14:06:16Z",
            actor: { kind: "system", id: "fixture-secret-posture" },
            entityId: "secret:ci-deploy-token",
            title: "Deployment credential posture",
            summary:
              "The credential is 183 days old, supports rotation, and grants one billing-api deployment permission.",
            caveat: "No credential material is included or returned.",
            toolName: "enrich_resource",
            payload: {
              kind: "secret_posture",
              classification: "production_deployment_credential",
              lastRotationDays: 183,
              rotateSupported: true,
              downstreamPermission: "deploy:billing-api",
            },
          },
          {
            ...base,
            id: "ENR-LAT-WORKLOAD-01",
            sequence: 30,
            status: "supporting",
            sourceCategory: "asset_inventory",
            sourceLabel: "workload inventory",
            timestamp: "2026-08-28T14:06:17Z",
            actor: { kind: "system", id: "fixture-workload-inventory" },
            entityId: "workload:billing-api",
            title: "Known-good workload image",
            summary:
              "A known-good image is available for a precautionary redeploy.",
            caveat:
              "No malicious deployment was observed and no workload is modified.",
            toolName: "enrich_resource",
            payload: {
              kind: "workload_recovery",
              environment: "production",
              currentImage: "billing-api:v2026.08.28.3",
              knownGoodImage: "billing-api:v2026.08.27.7",
              rollbackSupported: true,
            },
          },
        ],
        responseActionIds: [
          "rotate_deployment_credential",
          "rollback_workload_image",
        ],
      },
    ],
  },
  responseActions: [
    {
      id: "collect_endpoint_forensics",
      phase: "containment",
      title: "Collect forensic triage from FIN-WS-044",
      targetEntityId: "endpoint:fin-ws-044",
      requiresStageId: "STREAM-LAT-01",
      dependsOnActionIds: [],
      requiresEnrichmentIds: ["ENR-LAT-ENDPOINT-01"],
      evidenceIds: [
        "EVT-EDR-0448-01",
        "EVT-EDR-0448-03",
        "EVT-AUTH-0448-05",
        "EVT-EDR-0448-10",
      ],
      seversPathIds: [],
      requiresHumanAuthorization: true,
      executionScope: "synthetic_demo_only",
      preconditions: [
        "Healthy EDR sensor confirmed",
        "Process and network evidence attached",
        "Collection retention boundary confirmed",
      ],
      proposalReasoning:
        "Preserve an endpoint triage package before response changes the host state.",
      simulatedEffect:
        "A process tree, network summary, persistence triage, and Windows event export would be queued while the EDR channel remains available.",
      caveat:
        "No host is contacted, no memory is acquired, and no forensic artifact leaves this application.",
    },
    {
      id: "contain_endpoint",
      phase: "containment",
      title: "Contain FIN-WS-044",
      targetEntityId: "endpoint:fin-ws-044",
      requiresStageId: "STREAM-LAT-01",
      dependsOnActionIds: ["collect_endpoint_forensics"],
      requiresEnrichmentIds: ["ENR-LAT-FILE-01", "ENR-LAT-ENDPOINT-01"],
      evidenceIds: ["EVT-EDR-0448-01", "EVT-EDR-0448-03", "EVT-EDR-0448-10"],
      seversPathIds: ["PATH-LAT-EGRESS", "PATH-LAT-01"],
      requiresHumanAuthorization: true,
      executionScope: "synthetic_demo_only",
      preconditions: [
        "Endpoint and file context attached",
        "Remote service attempt observed",
        "Modeled effect attached",
      ],
      proposalReasoning:
        "Isolate FIN-WS-044 while preserving EDR collection and preventing new host-originated connections.",
      simulatedEffect:
        "FIN-WS-044 would lose non-EDR network access while remaining visible to collection.",
      caveat:
        "No endpoint is isolated and no external EDR system is contacted.",
    },
    {
      id: "block_network_indicator",
      phase: "containment",
      title: "Block 203.0.113.91 at egress",
      targetEntityId: "indicator:203.0.113.91",
      requiresStageId: "STREAM-LAT-01",
      dependsOnActionIds: [],
      requiresEnrichmentIds: ["ENR-LAT-DEST-01"],
      evidenceIds: ["EVT-EDR-0448-03", "EVT-EDR-0448-04"],
      seversPathIds: ["PATH-LAT-EGRESS"],
      requiresHumanAuthorization: true,
      executionScope: "synthetic_demo_only",
      preconditions: [
        "Destination context attached",
        "Both connections attributed to invoice-sync-helper.exe",
        "Exact host indicator confirmed",
      ],
      proposalReasoning:
        "Deny new outbound connections to the exact destination after process attribution and destination review.",
      simulatedEffect:
        "New egress connections to 203.0.113.91 would be denied while existing evidence remains in the case.",
      caveat:
        "No firewall or proxy control is changed and no external system is contacted.",
    },
    {
      id: "disable_service_identity",
      phase: "containment",
      title: "Disable svc-fin-reports",
      targetEntityId: "identity:svc-fin-reports",
      requiresStageId: "STREAM-LAT-01",
      dependsOnActionIds: [],
      requiresEnrichmentIds: ["ENR-LAT-IDENTITY-01", "ENR-LAT-APP-01"],
      evidenceIds: ["EVT-AUTH-0448-05", "EVT-EDR-0448-10", "EVT-CLOUD-0448-08"],
      seversPathIds: ["PATH-LAT-02", "PATH-LAT-03"],
      requiresHumanAuthorization: true,
      executionScope: "synthetic_demo_only",
      preconditions: [
        "Service identity baseline attached",
        "Unexpected authentication observed",
        "Modeled effect attached",
      ],
      proposalReasoning:
        "Disable new svc-fin-reports authentications before rotating its reachable deployment credential.",
      simulatedEffect:
        "New service-account logons and new secret reads would be denied. A credential already read would remain valid until rotation.",
      caveat: "No identity is disabled and no directory is contacted.",
    },
    {
      id: "rotate_deployment_credential",
      phase: "eradication",
      title: "Rotate ci/deploy/production",
      targetEntityId: "secret:ci-deploy-token",
      requiresStageId: "STREAM-LAT-02",
      dependsOnActionIds: ["disable_service_identity"],
      requiresEnrichmentIds: ["ENR-LAT-SECRET-01"],
      evidenceIds: ["EVT-CLOUD-0448-08", "EVT-CLOUD-0448-11"],
      seversPathIds: ["PATH-LAT-04"],
      requiresHumanAuthorization: true,
      executionScope: "synthetic_demo_only",
      preconditions: [
        "Service identity disablement approved",
        "Secret posture attached",
        "Modeled effect attached",
      ],
      proposalReasoning:
        "Rotate the deployment credential after disabling the service identity that read it.",
      simulatedEffect:
        "The current credential version would be invalidated and replaced without returning secret material.",
      caveat: "No key is rotated and no secret store is contacted.",
    },
    {
      id: "rollback_workload_image",
      phase: "recovery",
      title: "Redeploy known-good billing-api image",
      targetEntityId: "workload:billing-api",
      requiresStageId: "STREAM-LAT-02",
      dependsOnActionIds: ["rotate_deployment_credential"],
      requiresEnrichmentIds: ["ENR-LAT-WORKLOAD-01"],
      evidenceIds: ["EVT-CLOUD-0448-11", "EVT-CLOUD-0448-12"],
      seversPathIds: [],
      requiresHumanAuthorization: true,
      executionScope: "synthetic_demo_only",
      preconditions: [
        "Deployment credential rotation approved",
        "Known-good image attached",
        "Modeled effect attached",
      ],
      proposalReasoning:
        "Redeploy the known-good billing-api image as a precaution after rotating the exposed deployment credential.",
      simulatedEffect:
        "billing-api would be redeployed from the approved v2026.08.27.7 image without claiming that the current image is malicious.",
      caveat:
        "No malicious deployment was observed and no workload is changed.",
    },
  ],
  presentation: {
    defaultEvidenceView: "trace",
    graphWidth: 1320,
    graphHeight: 720,
    nodes: [
      { entityId: "file:invoice-sync-helper", x: 60, y: 130, lane: "entry" },
      { entityId: "endpoint:fin-ws-044", x: 300, y: 130, lane: "execution" },
      { entityId: "indicator:203.0.113.91", x: 560, y: 10, lane: "impact" },
      { entityId: "identity:svc-fin-reports", x: 560, y: 250, lane: "access" },
      { entityId: "endpoint:app-srv-021", x: 820, y: 90, lane: "lateral" },
      { entityId: "secret:ci-deploy-token", x: 820, y: 250, lane: "access" },
      { entityId: "workload:billing-api", x: 1080, y: 250, lane: "impact" },
    ],
    stageQuestions: [
      "Which observed execution, login, and command evidence proves the active chain before containment?",
      "Which controls halt new propagation while preserving evidence on both observed hosts?",
      "Which credential and workload recovery steps sever the remaining modeled path?",
    ],
    coverageNotes: [
      "Observed: helper execution, two TLS connections 60 seconds apart, service-account authentication, service-control commands, and a deployment-credential read. No remote payload execution, deployment, or exfiltration is claimed.",
      "The remote service start was blocked before execution. APP-SRV-021 remains affected by authentication evidence, not confirmed payload execution.",
      "Recovery inventory comes from the case snapshot. Credential rotation and image redeployment are simulated controls.",
    ],
    command: {
      observed: "Unsigned helper executed on FIN-WS-044",
      initialScope:
        "APP-SRV-021 authentication observed · remote execution not observed",
      stageScopes: [
        "APP-SRV-021 blocked remote service start before execution",
        "billing-api recovery inventory observed · no deployment observed",
      ],
      scopeMilestones: [],
    },
  },
  impact: {
    observedEntityIds: [
      "file:invoice-sync-helper",
      "endpoint:fin-ws-044",
      "indicator:203.0.113.91",
      "identity:svc-fin-reports",
      "endpoint:app-srv-021",
      "secret:ci-deploy-token",
    ],
    atRiskEntityIds: ["workload:billing-api"],
    blockedJoinIds: ["JOIN-LAT-06"],
    initialHeadline:
      "1 execution host · 1 targeted host · propagation scope pending",
    modeledHeadline:
      "1 execution host · 1 targeted host · 5 modeled risk segments",
    containedHeadline:
      "Propagation halted in the response model · recovery evidence retained",
  },
  conclusion: {
    reportId: "REPORT-ENDPOINT-0448",
    reportVersion: "case-report-v1",
    disposition: "confirmed_malicious_synthetic",
    title: "Multi-stage endpoint incident contained in the response model",
    executiveSummary:
      "Telemetry shows unsigned helper execution on FIN-WS-044, two TLS connections 60 seconds apart, an unexpected svc-fin-reports logon to APP-SRV-021, a blocked remote service-start attempt, and a production deployment-credential read. Forensic triage collection, endpoint isolation, destination blocking, identity disablement, credential rotation, and a known-good image redeploy were recorded as simulated approvals. No external system was contacted.",
    confirmedFindings: [
      "The unsigned helper executed on FIN-WS-044 and made two observed TLS connections separated by 60 seconds.",
      "svc-fin-reports authenticated to APP-SRV-021 outside its expected scope.",
      "APP-SRV-021 blocked the remote service-start attempt before execution.",
      "svc-fin-reports read the production deployment credential.",
    ],
    limitations: [
      "Destination ownership and connection content are unknown.",
      "No payload execution on APP-SRV-021, deployment, or data exfiltration is observed.",
      "Modeled reachability is not proof of compromise.",
    ],
    residualRisk: [
      "Validate APP-SRV-021 independently in a real response workflow.",
      "Review service-account scope before re-enablement.",
      "Preserve endpoint and authentication evidence for follow-up analysis.",
    ],
    requiredDecision: "confirmed_malicious",
    requiredEnrichmentIds: [
      "ENR-LAT-FILE-01",
      "ENR-LAT-HASH-04",
      "ENR-LAT-ENDPOINT-01",
      "ENR-LAT-IDENTITY-01",
      "ENR-LAT-DEST-01",
      "ENR-LAT-APP-01",
      "ENR-LAT-SECRET-01",
      "ENR-LAT-WORKLOAD-01",
    ],
    requiredActionIds: [
      "collect_endpoint_forensics",
      "contain_endpoint",
      "block_network_indicator",
      "disable_service_identity",
      "rotate_deployment_credential",
      "rollback_workload_image",
    ],
  },
} satisfies CaseFixture;
