"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import {
  analystClosureNoteMaxLength,
  analystClosureNoteMinLength,
} from "@/domain/report-signoff";
import type {
  AnalystReportSignoff,
  CaseFixture,
  CaseState,
  OperationReceipt,
} from "@/domain/types";
import type { EvidenceProvenanceTargetType } from "./trace-interaction";

interface CaseReportPanelProps {
  approvalReceipt: OperationReceipt | null;
  busy: boolean;
  fixture: CaseFixture;
  findingsSectionId: string;
  onApprove: (signoff: AnalystReportSignoff) => Promise<void>;
  onViewProvenance: (target: {
    targetId: string;
    targetType: EvidenceProvenanceTargetType;
  }) => void;
  reportId: string;
  state: CaseState;
}

export function CaseReportPanel({
  approvalReceipt,
  busy,
  fixture,
  findingsSectionId,
  onApprove,
  onViewProvenance,
  reportId,
  state,
}: CaseReportPanelProps) {
  const [closureNote, setClosureNote] = useState("");
  const documentRef = useRef<HTMLElement>(null);
  const reportApproved = state.report.status === "approved_in_demo";

  useEffect(() => {
    if (!reportApproved) return;
    const frame = window.requestAnimationFrame(() => {
      documentRef.current
        ?.querySelector<HTMLElement>("h3")
        ?.focus({ preventScroll: true });
      documentRef.current?.scrollIntoView({ behavior: "auto", block: "start" });
    });
    return () => window.cancelAnimationFrame(frame);
  }, [reportApproved, state.report.approvedAt]);

  if (state.decision.status === "pending") return null;
  if (state.report.status === "unavailable") return null;

  const report = state.report.report;
  if (!report) return null;
  const approved = reportApproved;
  const recordedActions = report.actionIds.flatMap((actionId) => {
    const action = fixture.responseActions.find(
      (candidate) => candidate.id === actionId,
    );
    return action ? [action] : [];
  });
  const availableEnrichments = [
    ...fixture.enrichments,
    ...fixture.stream.stages.flatMap((stage) => stage.enrichments),
  ];
  const evidenceFindings = availableEnrichments.filter((artifact) =>
    report.evidenceIds.includes(artifact.id),
  );
  const hashArtifact = evidenceFindings.find(
    (artifact) => artifact.payload.kind === "hash_intelligence_fixture",
  );
  const keyHash =
    hashArtifact?.payload.kind === "hash_intelligence_fixture"
      ? hashArtifact.payload.sha256
      : null;
  const normalizedNoteLength = closureNote.trim().length;
  const canApprove =
    normalizedNoteLength >= analystClosureNoteMinLength &&
    normalizedNoteLength <= analystClosureNoteMaxLength;
  const approvalActor = approvalReceipt
    ? receiptActorLabel(approvalReceipt)
    : "Operator";

  return (
    <article
      aria-label="Case evidence report"
      className={`case-report-document ${approved ? "case-report-approved" : ""}`}
      id={reportId}
      ref={documentRef}
    >
      <p aria-live="polite" className="sr-only">
        {approved
          ? "Case report approved and case closed."
          : "Evidence report draft ready for operator approval."}
      </p>
      <header className="report-document-header">
        <div>
          <p>
            Case report · {report.version} · Generated by TRACE at{" "}
            {formatUtcTime(report.generatedAt)}
          </p>
          <h3 tabIndex={-1}>{report.title}</h3>
        </div>
        <span>{approved ? "Approved" : "Draft"}</span>
      </header>

      {approved ? (
        <section
          aria-label="Operator approval record"
          className="report-approval-record"
        >
          <div>
            <span>{approvalActor}-approved evidence report</span>
            <strong>
              {evidenceFindings.length} findings · {recordedActions.length}{" "}
              recorded controls · shared revision r{state.revision}
            </strong>
            <small>
              Approved {formatUtcTime(state.report.approvedAt)} · modeled case
              record · no external control executed
            </small>
            {approvalReceipt ? (
              <small>
                Approval receipt {approvalReceipt.id} · {approvalActor} · r
                {approvalReceipt.baseRevision}→r
                {approvalReceipt.resultRevision}
              </small>
            ) : null}
            <small>
              {approvalActor} channel recorded · WebMCP cannot invoke this
              control
            </small>
          </div>
          <blockquote>{state.report.analystClosureNote}</blockquote>
        </section>
      ) : null}

      <section className="report-document-section report-assessment">
        <p className="report-section-label">Assessment</p>
        <strong>{formatReportDisposition(report.disposition)}</strong>
        <p>{report.executiveSummary}</p>
        {keyHash ? (
          <div className="report-inline-indicator">
            <span>Key indicator · SHA-256</span>
            <code>{keyHash}</code>
          </div>
        ) : null}
      </section>

      <section className="report-document-section">
        <div className="report-section-heading">
          <div>
            <p className="report-section-label">Evidence basis</p>
            <h4>Findings supporting the assessment</h4>
          </div>
          <a href={`#${findingsSectionId}`}>Open source records</a>
        </div>
        <div className="report-evidence-table" role="table">
          <div className="report-evidence-table-head" role="row">
            <span role="columnheader">Reference</span>
            <span role="columnheader">Finding</span>
            <span role="columnheader">Source</span>
            <span role="columnheader">Assessment</span>
          </div>
          {evidenceFindings.map((finding, index) => (
            <div className="report-evidence-row" key={finding.id} role="row">
              <code role="cell">F-{String(index + 1).padStart(2, "0")}</code>
              <div role="cell">
                <strong>{finding.title}</strong>
                <p>{finding.summary}</p>
                <button
                  aria-label={`View provenance for F-${String(index + 1).padStart(2, "0")}: ${finding.title}`}
                  className="report-evidence-provenance"
                  onClick={() =>
                    onViewProvenance({
                      targetId: finding.id,
                      targetType: "report_finding",
                    })
                  }
                  type="button"
                >
                  View provenance
                </button>
              </div>
              <span role="cell">{finding.sourceLabel}</span>
              <span
                className={`report-truth-status is-${finding.status}`}
                role="cell"
              >
                {finding.status}
              </span>
            </div>
          ))}
        </div>
        {state.decision.rationale ? (
          <div className="report-analyst-decision">
            <span>Operator decision</span>
            <p>{state.decision.rationale}</p>
          </div>
        ) : null}
      </section>

      <section className="report-document-section">
        <p className="report-section-label">Response record</p>
        {recordedActions.length > 0 ? (
          <ol className="report-response-ledger">
            {recordedActions.map((action) => (
              <li key={action.id}>
                <div>
                  <strong>{action.title}</strong>
                  <span>{action.targetEntityId}</span>
                </div>
                <span>{approvalActor} authorized</span>
                <small>Recorded only · no external execution</small>
              </li>
            ))}
          </ol>
        ) : (
          <p className="report-empty-response">
            No containment action was required for this disposition.
          </p>
        )}
      </section>

      <section className="report-document-section report-risk-section">
        <div>
          <p className="report-section-label">Residual risk</p>
          <ul>
            {report.residualRisk.map((risk) => (
              <li key={risk}>{risk}</li>
            ))}
          </ul>
        </div>
        <div>
          <p className="report-section-label">Known limitations</p>
          <ul>
            {report.limitations.map((limitation) => (
              <li key={limitation}>{limitation}</li>
            ))}
          </ul>
        </div>
      </section>

      <details className="report-provenance-disclosure">
        <summary>Generation provenance and immutable references</summary>
        <p>
          Drafted from {evidenceFindings.length} attached investigation
          findings, {report.evidenceIds.length} immutable evidence references,
          and {report.actionIds.length} operator-authorized response records.
        </p>
        <code>{report.evidenceIds.join(" · ")}</code>
      </details>

      {!approved ? (
        <form
          className="report-signoff-form"
          onSubmit={(event) => {
            event.preventDefault();
            if (canApprove) void onApprove({ analystClosureNote: closureNote });
          }}
        >
          <div className="report-signoff-copy">
            <p className="report-section-label">Analyst approval</p>
            <h4>Record the basis for closure</h4>
            <p>
              The generated evidence remains read-only. Your closure note is
              retained with this report revision.
            </p>
          </div>
          <label htmlFor={`${reportId}-closure-note`}>Closure note</label>
          <textarea
            aria-describedby={`${reportId}-closure-guidance`}
            id={`${reportId}-closure-note`}
            maxLength={analystClosureNoteMaxLength}
            onChange={(event) => setClosureNote(event.target.value)}
            placeholder="Record the closure basis, policy exception or containment outcome, and remaining follow-up."
            rows={4}
            value={closureNote}
          />
          <div className="report-signoff-footer">
            <p id={`${reportId}-closure-guidance`}>
              {normalizedNoteLength}/{analystClosureNoteMaxLength} characters ·
              minimum {analystClosureNoteMinLength}. Closing records approval;
              it does not execute an external action.
            </p>
            <button disabled={busy || !canApprove} type="submit">
              {busy ? "Recording approval" : "Approve and close case"}
            </button>
          </div>
        </form>
      ) : (
        <section className="report-approval-summary">
          <p className="report-section-label">{approvalActor} approval</p>
          <blockquote>{state.report.analystClosureNote}</blockquote>
          <p>
            Approved {formatUtcTime(state.report.approvedAt)} · No external
            system was contacted.
          </p>
          {fixture.id === "case-cloud-0421" ? (
            <Link href="/cases/case-endpoint-0448">
              Open next escalation <span aria-hidden="true">→</span>
            </Link>
          ) : (
            <Link href="/alerts">Return to incident ledger</Link>
          )}
        </section>
      )}
    </article>
  );
}

function receiptActorLabel(receipt: OperationReceipt): string {
  switch (receipt.actorAssurance) {
    case "anonymous_sandbox":
      return "Anonymous operator";
    case "cloudflare_access_verified":
    case "openai_sites_authenticated":
      return "Verified analyst";
    case "local_development":
      return "Local analyst";
    default:
      return "Operator";
  }
}

function formatReportDisposition(
  disposition: NonNullable<CaseState["report"]["report"]>["disposition"],
): string {
  return disposition === "authorized_activity_policy_exception"
    ? "Authorized activity · policy exception"
    : "Confirmed malicious activity";
}

function formatUtcTime(value: string | null): string {
  if (!value) return "—";
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return value;
  return `${parsed.toISOString().slice(11, 19)}Z`;
}
